/*
 * This source code was auto-generated by TypeContractor.
 * Changes to this file may cause incorrect behavior and will be lost when the
 * code is regenerated next time TypeContractor runs.
 */
import { z } from 'zod';
import { ProviderType } from '../Domain/ProviderType';
import { AuthState } from '../Domain/AuthState';

export interface AccountDto {
  id: string;
  displayName: string;
  emailAddress: string;
  providerType: ProviderType;
  authState: AuthState;
  isEnabled: boolean;
  lastAuthError?: string;
  color: string;
  sortOrder: number;
}

export const AccountDtoSchema = z.object({
  id: z.string().uuid(),
  displayName: z.string(),
  emailAddress: z.string(),
  providerType: z.nativeEnum(ProviderType),
  authState: z.nativeEnum(AuthState),
  isEnabled: z.boolean(),
  lastAuthError: z.string().nullable(),
  color: z.string(),
  sortOrder: z.number(),
});
