/*
 * This source code was auto-generated by TypeContractor.
 * Changes to this file may cause incorrect behavior and will be lost when the
 * code is regenerated next time TypeContractor runs.
 */
import { z } from 'zod';
import { ProviderType } from '../Domain/ProviderType';
import { ImapAccountSettings, ImapAccountSettingsSchema } from './ImapAccountSettings';
import { CalDavAccountSettings, CalDavAccountSettingsSchema } from './CalDavAccountSettings';
import { CertificateTrustMode } from '../Domain/CertificateTrustMode';

export interface AddAccountRequest {
  displayName: string;
  providerType: ProviderType;
  emailAddress: string;
  secret?: string;
  imap?: ImapAccountSettings;
  calDav?: CalDavAccountSettings;
  certificateTrustMode: CertificateTrustMode;
}

export const AddAccountRequestSchema = z.object({
  displayName: z.string(),
  providerType: z.nativeEnum(ProviderType),
  emailAddress: z.string(),
  secret: z.string().nullable(),
  imap: ImapAccountSettingsSchema.nullable(),
  calDav: CalDavAccountSettingsSchema.nullable(),
  certificateTrustMode: z.nativeEnum(CertificateTrustMode),
});
