/*
 * This source code was auto-generated by TypeContractor.
 * Changes to this file may cause incorrect behavior and will be lost when the
 * code is regenerated next time TypeContractor runs.
 */
import { z } from 'zod';

export interface CalDavAccountSettings {
  endpoint: string;
  userName: string;
  reuseImapCredential: boolean;
  secret?: string;
}

export const CalDavAccountSettingsSchema = z.object({
  endpoint: z.string(),
  userName: z.string(),
  reuseImapCredential: z.boolean(),
  secret: z.string().nullable(),
});
