/*
 * This source code was auto-generated by TypeContractor.
 * Changes to this file may cause incorrect behavior and will be lost when the
 * code is regenerated next time TypeContractor runs.
 */
import { z } from 'zod';

export interface ImapAccountSettings {
  host: string;
  port: number;
  useSsl: boolean;
  userName: string;
  smtpHost: string;
  smtpPort: number;
  reuseImapCredentialForSmtp: boolean;
  smtpSecret?: string;
}

export const ImapAccountSettingsSchema = z.object({
  host: z.string(),
  port: z.number(),
  useSsl: z.boolean(),
  userName: z.string(),
  smtpHost: z.string(),
  smtpPort: z.number(),
  reuseImapCredentialForSmtp: z.boolean(),
  smtpSecret: z.string().nullable(),
});
