/*
 * This source code was auto-generated by TypeContractor.
 * Changes to this file may cause incorrect behavior and will be lost when the
 * code is regenerated next time TypeContractor runs.
 */
import { z } from 'zod';

export interface LastViewedMailboxDto {
  accountId?: string;
  mailboxId?: string;
}

export const LastViewedMailboxDtoSchema = z.object({
  accountId: z.string().uuid().nullable(),
  mailboxId: z.string().uuid().nullable(),
});
