/*
 * This source code was auto-generated by TypeContractor.
 * Changes to this file may cause incorrect behavior and will be lost when the
 * code is regenerated next time TypeContractor runs.
 */
import { z } from 'zod';
import { RemoteContentRuleScope } from '../Domain/RemoteContentRuleScope';
import { RemoteContentRuleDecision } from '../Domain/RemoteContentRuleDecision';

export interface PutRemoteContentRuleRequest {
  scope: RemoteContentRuleScope;
  decision: RemoteContentRuleDecision;
  value: string;
}

export const PutRemoteContentRuleRequestSchema = z.object({
  scope: z.nativeEnum(RemoteContentRuleScope),
  decision: z.nativeEnum(RemoteContentRuleDecision),
  value: z.string(),
});
