/*
 * This source code was auto-generated by TypeContractor.
 * Changes to this file may cause incorrect behavior and will be lost when the
 * code is regenerated next time TypeContractor runs.
 */
import { z } from 'zod';

export interface ReauthenticateAccountRequest {
  secret?: string;
}

export const ReauthenticateAccountRequestSchema = z.object({
  secret: z.string().nullable(),
});
