/*
 * This source code was auto-generated by TypeContractor.
 * Changes to this file may cause incorrect behavior and will be lost when the
 * code is regenerated next time TypeContractor runs.
 */
import { z } from 'zod';
import { RemoteContentRuleScope } from '../Domain/RemoteContentRuleScope';
import { RemoteContentRuleDecision } from '../Domain/RemoteContentRuleDecision';

export interface RemoteContentRuleDto {
  id: string;
  scope: RemoteContentRuleScope;
  decision: RemoteContentRuleDecision;
  value: string;
}

export const RemoteContentRuleDtoSchema = z.object({
  id: z.string().uuid(),
  scope: z.nativeEnum(RemoteContentRuleScope),
  decision: z.nativeEnum(RemoteContentRuleDecision),
  value: z.string(),
});
