/*
 * This source code was auto-generated by TypeContractor.
 * Changes to this file may cause incorrect behavior and will be lost when the
 * code is regenerated next time TypeContractor runs.
 */
import { z } from 'zod';

export interface ShellSettingsDto {
  panelLayout?: string;
  windowBoundsJson?: string;
  mailtoPromptDismissed: boolean;
}

export const ShellSettingsDtoSchema = z.object({
  panelLayout: z.string().nullable(),
  windowBoundsJson: z.string().nullable(),
  mailtoPromptDismissed: z.boolean(),
});
