/*
 * This source code was auto-generated by TypeContractor.
 * Changes to this file may cause incorrect behavior and will be lost when the
 * code is regenerated next time TypeContractor runs.
 */
import { z } from 'zod';
import { ThemePreference } from '../Domain/ThemePreference';

export interface UpdateThemeRequest {
  theme: ThemePreference;
}

export const UpdateThemeRequestSchema = z.object({
  theme: z.nativeEnum(ThemePreference),
});
