/*
 * This source code was auto-generated by TypeContractor.
 * Changes to this file may cause incorrect behavior and will be lost when the
 * code is regenerated next time TypeContractor runs.
 */
import { z } from 'zod';
import { CloseBehavior } from '../Domain/CloseBehavior';

export interface UpdateCloseBehaviorRequest {
  closeBehavior: CloseBehavior;
}

export const UpdateCloseBehaviorRequestSchema = z.object({
  closeBehavior: z.nativeEnum(CloseBehavior),
});
