// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MyloMail.Api.Persistence.Migrations;

[DbContext(typeof(MyloMailDbContext))]
[Migration("20260914000000_AddRemovalRecoveryAndTopologyEpoch")]
partial class AddRemovalRecoveryAndTopologyEpoch
{
	protected override void BuildTargetModel(ModelBuilder modelBuilder)
	{
#pragma warning disable 612, 618
		modelBuilder.HasAnnotation("ProductVersion", "10.0.11");
#pragma warning restore 612, 618
	}
}
