// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyloMail.Api.Persistence;

#nullable disable

namespace MyloMail.Api.Persistence.Migrations
{
    [DbContext(typeof(MyloMailDbContext))]
    partial class MyloMailDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("MyloMail.Api.Domain.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("AttachmentSizeLimitOverride")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthState")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CertificateTrustMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactSyncCursor")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("InitialSyncBoundValue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InitialSyncMode")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastAuthError")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("NotificationEpoch")
                        .HasColumnType("TEXT");

                    b.Property<bool>("NotificationsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PollIntervalSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PollingEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProviderConfig")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProviderType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SidebarCollapsed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UndoSendDelaySeconds")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("MyloMail.Api.Domain.AccountTrustedCertificate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpectedHostname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sha256Fingerprint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "ExpectedHostname", "Sha256Fingerprint")
                        .IsUnique();

                    b.ToTable("AccountTrustedCertificates");
                });

            modelBuilder.Entity("MyloMail.Api.Domain.AppSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AttachmentTempCleanupOnStartup")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CloseBehavior")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MailtoPromptDismissed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MessageThreadBackfillVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PanelLayout")
                        .HasColumnType("TEXT");

                    b.Property<int>("Theme")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WindowBoundsJson")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppSettings", t =>
                        {
                            t.HasCheckConstraint("CK_AppSettings_SingleRow", "\"Id\" = 1");
                        });
                });

            modelBuilder.Entity("MyloMail.Api.Domain.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsInline")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PartSpecifier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RawVersion")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("MyloMail.Api.Domain.Calendar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Colour")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLocalOnly")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderCalendarId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncCursor")
                        .HasColumnType("TEXT");

                    b.Property<bool>("SyncWindowRebasing")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("SyncWindowStartedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "ProviderCalendarId")
                        .IsUnique();

                    b.ToTable("Calendars");
                });

            modelBuilder.Entity("MyloMail.Api.Domain.CalendarEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Attendees")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CalendarId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("End")
                        .HasColumnType("TEXT");

                    b.Property<string>("EndTimeZoneId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExceptionDates")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ICalUid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAllDay")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<string>("Organizer")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderEventId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderRevision")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecurrenceDates")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("RecurrenceId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RecurrenceMasterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecurrenceMasterProviderEventId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecurrenceRules")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reminders")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("Start")
                        .HasColumnType("TEXT");

                    b.Property<string>("StartTimeZoneId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SyncConflict")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ICalUid");

                    b.HasIndex("CalendarId", "ProviderEventId")
                        .IsUnique();


                    b.ToTable("CalendarEvents");
                });
            modelBuilder.Entity("MyloMail.Api.Domain.CalendarCreationAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CalendarId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DispatchedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("End")
                        .HasColumnType("TEXT");

                    b.Property<string>("ICalUid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAllDay")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderCreationKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Start")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CalendarId");

                    b.ToTable("CalendarCreationAttempts");
                });

            modelBuilder.Entity("MyloMail.Api.Domain.ChangeStreamState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("BaselineEstablishedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CursorKind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CursorState")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRebasing")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MailboxId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("NotificationBaselineAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique()
                        .HasFilter("\"MailboxId\" IS NULL");

                    b.HasIndex("MailboxId");

                    b.HasIndex("AccountId", "MailboxId")
                        .IsUnique();

                    b.ToTable("ChangeStreamStates");
                });

            modelBuilder.Entity("MyloMail.Api.Domain.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderContactId")
                        .HasColumnType("TEXT");
                    b.Property<string>("ProviderContainerId")
                        .HasColumnType("TEXT");


                    b.Property<string>("ProviderRevision")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ProviderMissingSince")
                        .HasColumnType("TEXT");

                    b.Property<bool>("SyncConflict")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "ProviderContactId")
                        .IsUnique();

                    b.ToTable("Contacts");
                });


            modelBuilder.Entity("MyloMail.Api.Domain.ContactSuggestion", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AccountId", "NormalizedEmail");

                    b.ToTable("ContactSuggestions");
                });

            modelBuilder.Entity("MyloMail.Api.Domain.ContactOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("TEXT");
                    b.Property<long>("Sequence")
                        .HasColumnType("INTEGER");


                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpectedRevision")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DispatchedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("SettledAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");
                    b.HasIndex("ContactId", "Sequence")
                        .IsUnique();


                    b.HasIndex("State", "CreatedAt");

                    b.ToTable("ContactOperations");
                });

            modelBuilder.Entity("MyloMail.Api.Domain.ContactAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContactId", "NormalizedEmail")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail");

                    b.ToTable("ContactAddresses");
                });

            modelBuilder.Entity("MyloMail.Api.Domain.CredentialFallbackSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("VerifierCiphertext")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("VerifierNonce")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("VerifierTag")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.ToTable("CredentialFallbackSettings", t =>
                        {
                            t.HasCheckConstraint("CK_CredentialFallbackSettings_SingleRow", "\"Id\" = 1");
                        });
                });

            modelBuilder.Entity("MyloMail.Api.Domain.Draft", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Attachments")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Bcc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BodyHtml")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("InReplyToMessageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDraftId")
                        .HasColumnType("TEXT");

					b.Property<string>("ProviderMessageId")
						.HasColumnType("TEXT");

                    b.Property<string>("ProviderRevision")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("PushDispatchedForSavedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("PushedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("SavedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SendIdentityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StableMessageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("SyncConflict")
                        .HasColumnType("INTEGER");

                    b.Property<string>("To")

                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("SendIdentityId");

                    b.ToTable("Drafts");
                });

            modelBuilder.Entity("MyloMail.Api.Domain.EncryptedCredential", b =>
                {
                    b.Property<Guid>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Ciphertext")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("Nonce")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("Tag")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("AccountId");

                    b.ToTable("EncryptedCredentials");
                });

            modelBuilder.Entity("MyloMail.Api.Domain.ExportJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinationPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<string>("ManifestJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ResumeToken")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WrittenCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("Status");

                    b.ToTable("ExportJobs");
                });

            modelBuilder.Entity("MyloMail.Api.Domain.ImapMailboxMetadata", b =>
                {
                    b.Property<Guid>("MailboxId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<char>("HierarchyDelimiter")
                        .HasColumnType("TEXT");

                    b.Property<string>("NamespacePrefix")
                        .HasColumnType("TEXT");

                    b.HasKey("MailboxId");

                    b.ToTable("ImapMailboxMetadata");
                });

            modelBuilder.Entity("MyloMail.Api.Domain.IntegrityReconciliationState", b =>
                {
                    b.Property<Guid>("MailboxId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastReconciledAt")
                        .HasColumnType("TEXT");

                    b.HasKey("MailboxId");

                    b.ToTable("IntegrityReconciliationStates");
                });

            modelBuilder.Entity("MyloMail.Api.Domain.Mailbox", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("InitialSyncBoundValueOverride")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("InitialSyncModeOverride")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCollapsed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSubscribed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocalSortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderMailboxId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProviderTotalCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProviderUnreadCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpecialUse")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SpecialUseOverride")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TopologyGeneration")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("AccountId", "ProviderMailboxId")
                        .IsUnique();

                    b.ToTable("Mailboxes");
                });

            modelBuilder.Entity("MyloMail.Api.Domain.MailboxCoverageState", b =>
                {
                    b.Property<Guid>("MailboxId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EstimatedTotal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<int>("MessagesFetched")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResumeToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("MailboxId");

                    b.ToTable("MailboxCoverageStates");
                });

            modelBuilder.Entity("MyloMail.Api.Domain.MailboxTopologySyncState", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cursor")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastReconciledAt")
                        .HasColumnType("TEXT");

                    b.HasKey("AccountId");

                    b.ToTable("MailboxTopologySyncStates");
                });

            modelBuilder.Entity("MyloMail.Api.Domain.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Bcc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasNonInlineAttachments")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InReplyToHeader")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAnswered")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDraft")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFlagged")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MessageIdHeader")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("OrphanedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderStableId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("RawFetched")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferencesHeader")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReplyToAddresses")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SenderAddress")
                        .HasColumnType("TEXT");

                    b.Property<long?>("SizeEstimate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Snippet")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasProviderThreadId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ThreadId")
                        .HasColumnType("TEXT");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "MessageIdHeader");

                    b.HasIndex("AccountId", "ProviderStableId")
                        .IsUnique();

                    b.HasIndex("AccountId", "ReceivedAt");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("MyloMail.Api.Domain.MessageBody", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("HtmlBody")
                        .HasColumnType("TEXT");

                    b.Property<string>("TextBody")
                        .HasColumnType("TEXT");

                    b.HasKey("MessageId");

                    b.ToTable("MessageBodies");
                });

            modelBuilder.Entity("MyloMail.Api.Domain.MessageContentState", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<int>("RawVersion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("MessageId");

                    b.HasIndex("Status");

                    b.ToTable("MessageContentStates");
                });

            modelBuilder.Entity("MyloMail.Api.Domain.MessageHeaders", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Headers")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MessageId");

                    b.ToTable("MessageHeaders");
                });

            modelBuilder.Entity("MyloMail.Api.Domain.MessageMailbox", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long?>("ImapModSeq")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MailboxId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderOccurrenceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MailboxId", "ProviderOccurrenceId")
                        .IsUnique();

                    b.HasIndex("MessageId", "MailboxId")
                        .IsUnique();

                    b.ToTable("MessageMailboxes");
                });

            modelBuilder.Entity("MyloMail.Api.Domain.MessagePendingChange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("DesiredValue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Field")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MutationItemId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MutationItemId");

                    b.HasIndex("MessageId", "Field")
                        .IsUnique();

                    b.ToTable("MessagePendingChanges");
                });

            modelBuilder.Entity("MyloMail.Api.Domain.MessageRaw", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("MessageId");

                    b.ToTable("MessageRaws");
                });

            modelBuilder.Entity("MyloMail.Api.Domain.MessageSearchContent", b =>
                {
                    b.Property<long>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BodyText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CcAddresses")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FromAddresses")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ToAddresses")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RowId");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.ToTable("MessageSearchContents");
                });

            modelBuilder.Entity("MyloMail.Api.Domain.MutationExecutionAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DispatchedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("OperationKind")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("OutboxItemId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Provider")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ResultPersistedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("OutboxItemId");

                    b.HasIndex("State", "ResultPersistedAt");

                    b.ToTable("MutationExecutionAttempts");
                });

            modelBuilder.Entity("MyloMail.Api.Domain.MutationExecutionAttemptItem", b =>
                {
                    b.Property<Guid>("AttemptId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MutationItemId")
                        .HasColumnType("TEXT");

                    b.HasKey("AttemptId", "MutationItemId");

                    b.HasIndex("MutationItemId");

                    b.ToTable("MutationExecutionAttemptItems");
                });

            modelBuilder.Entity("MyloMail.Api.Domain.MutationItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DependsOnMutationItemId")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("DesiredIsFlagged")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("DesiredIsRead")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FailureCategory")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LeaseExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LeaseOwner")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("TEXT");

                    b.Property<int>("OperationKind")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ScopeMailboxId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("TargetMailboxId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.HasIndex("AccountId", "State");

                    b.HasIndex("AccountId", "MessageId", "Sequence")
                        .IsUnique();

                    b.ToTable("MutationItems");
                });

            modelBuilder.Entity("MyloMail.Api.Domain.NotificationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("MessageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderStableId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeliveredAt");

                    b.HasIndex("MessageId");

                    b.HasIndex("AccountId", "MessageId", "Kind")
                        .IsUnique()
                        .HasFilter("\"MessageId\" IS NOT NULL");

                    b.HasIndex("AccountId", "ProviderStableId", "Kind")
                        .IsUnique()
                        .HasFilter("\"ProviderStableId\" IS NOT NULL");

                    b.ToTable("NotificationRecords");
                });

            modelBuilder.Entity("MyloMail.Api.Domain.OutboxItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DraftId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecipientSnapshot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ReconcilingSince")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ScheduledSendAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("StableMessageId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StableMessageId")
                        .IsUnique();

                    b.HasIndex("AccountId", "Status");

                    b.ToTable("OutboxItems");
                });

            modelBuilder.Entity("MyloMail.Api.Domain.SendIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SignatureHtml")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique()
                        .HasDatabaseName("IX_SendIdentities_AccountId_Default")
                        .HasFilter("\"IsDefault\" = 1");

                    b.ToTable("SendIdentities");
                });

            modelBuilder.Entity("MyloMail.Api.Domain.StagedChangeEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ScannedForNotifications")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("StagedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "Ordinal")
                        .IsUnique();

                    b.ToTable("StagedChangeEvents");
                });

            modelBuilder.Entity("MyloMail.Api.Domain.TrustedRemoteContentSender", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Address")
                        .IsUnique();

                    b.ToTable("TrustedRemoteContentSenders");
                });

            modelBuilder.Entity("MyloMail.Api.Domain.AccountTrustedCertificate", b =>
                {
                    b.HasOne("MyloMail.Api.Domain.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyloMail.Api.Domain.Attachment", b =>
                {
                    b.HasOne("MyloMail.Api.Domain.Message", null)
                        .WithMany()
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyloMail.Api.Domain.Calendar", b =>
                {
                    b.HasOne("MyloMail.Api.Domain.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyloMail.Api.Domain.CalendarEvent", b =>
                {
                    b.HasOne("MyloMail.Api.Domain.Calendar", null)
                        .WithMany()
                        .HasForeignKey("CalendarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyloMail.Api.Domain.CalendarCreationAttempt", b =>
                {
                    b.HasOne("MyloMail.Api.Domain.Calendar", null)
                        .WithMany()
                        .HasForeignKey("CalendarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyloMail.Api.Domain.Contact", b =>
                {
                    b.HasOne("MyloMail.Api.Domain.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyloMail.Api.Domain.ContactAddress", b =>
                {
                    b.HasOne("MyloMail.Api.Domain.Contact", "Contact")
                        .WithMany("Addresses")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyloMail.Api.Domain.ContactOperation", b =>
                {
                    b.HasOne("MyloMail.Api.Domain.Contact", null)
                        .WithMany()
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });


            modelBuilder.Entity("MyloMail.Api.Domain.ContactSuggestion", b =>
                {
                    b.HasOne("MyloMail.Api.Domain.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyloMail.Api.Domain.ChangeStreamState", b =>
                {
                    b.HasOne("MyloMail.Api.Domain.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyloMail.Api.Domain.Mailbox", null)
                        .WithMany()
                        .HasForeignKey("MailboxId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MyloMail.Api.Domain.Draft", b =>
                {
                    b.HasOne("MyloMail.Api.Domain.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyloMail.Api.Domain.SendIdentity", null)
                        .WithMany()
                        .HasForeignKey("SendIdentityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MyloMail.Api.Domain.ExportJob", b =>
                {
                    b.HasOne("MyloMail.Api.Domain.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyloMail.Api.Domain.ImapMailboxMetadata", b =>
                {
                    b.HasOne("MyloMail.Api.Domain.Mailbox", null)
                        .WithOne("ImapMetadata")
                        .HasForeignKey("MyloMail.Api.Domain.ImapMailboxMetadata", "MailboxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyloMail.Api.Domain.IntegrityReconciliationState", b =>
                {
                    b.HasOne("MyloMail.Api.Domain.Mailbox", null)
                        .WithOne()
                        .HasForeignKey("MyloMail.Api.Domain.IntegrityReconciliationState", "MailboxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyloMail.Api.Domain.Mailbox", b =>
                {
                    b.HasOne("MyloMail.Api.Domain.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyloMail.Api.Domain.Mailbox", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("MyloMail.Api.Domain.MailboxCoverageState", b =>
                {
                    b.HasOne("MyloMail.Api.Domain.Mailbox", null)
                        .WithOne()
                        .HasForeignKey("MyloMail.Api.Domain.MailboxCoverageState", "MailboxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyloMail.Api.Domain.MailboxTopologySyncState", b =>
                {
                    b.HasOne("MyloMail.Api.Domain.Account", null)
                        .WithOne()
                        .HasForeignKey("MyloMail.Api.Domain.MailboxTopologySyncState", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyloMail.Api.Domain.Message", b =>
                {
                    b.HasOne("MyloMail.Api.Domain.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyloMail.Api.Domain.MessageBody", b =>
                {
                    b.HasOne("MyloMail.Api.Domain.Message", null)
                        .WithOne()
                        .HasForeignKey("MyloMail.Api.Domain.MessageBody", "MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyloMail.Api.Domain.MessageContentState", b =>
                {
                    b.HasOne("MyloMail.Api.Domain.Message", null)
                        .WithOne()
                        .HasForeignKey("MyloMail.Api.Domain.MessageContentState", "MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyloMail.Api.Domain.MessageHeaders", b =>
                {
                    b.HasOne("MyloMail.Api.Domain.Message", null)
                        .WithOne()
                        .HasForeignKey("MyloMail.Api.Domain.MessageHeaders", "MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyloMail.Api.Domain.MessageMailbox", b =>
                {
                    b.HasOne("MyloMail.Api.Domain.Mailbox", null)
                        .WithMany()
                        .HasForeignKey("MailboxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyloMail.Api.Domain.Message", null)
                        .WithMany("Occurrences")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyloMail.Api.Domain.MessagePendingChange", b =>
                {
                    b.HasOne("MyloMail.Api.Domain.MutationItem", null)
                        .WithMany()
                        .HasForeignKey("MutationItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyloMail.Api.Domain.MessageRaw", b =>
                {
                    b.HasOne("MyloMail.Api.Domain.Message", null)
                        .WithOne()
                        .HasForeignKey("MyloMail.Api.Domain.MessageRaw", "MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyloMail.Api.Domain.MessageSearchContent", b =>
                {
                    b.HasOne("MyloMail.Api.Domain.Message", null)
                        .WithMany()
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MyloMail.Api.Domain.MutationExecutionAttempt", b =>
                {
                    b.HasOne("MyloMail.Api.Domain.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyloMail.Api.Domain.OutboxItem", null)
                        .WithMany()
                        .HasForeignKey("OutboxItemId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MyloMail.Api.Domain.MutationExecutionAttemptItem", b =>
                {
                    b.HasOne("MyloMail.Api.Domain.MutationExecutionAttempt", null)
                        .WithMany("Items")
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyloMail.Api.Domain.MutationItem", null)
                        .WithMany()
                        .HasForeignKey("MutationItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyloMail.Api.Domain.MutationItem", b =>
                {
                    b.HasOne("MyloMail.Api.Domain.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyloMail.Api.Domain.NotificationRecord", b =>
                {
                    b.HasOne("MyloMail.Api.Domain.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyloMail.Api.Domain.Message", null)
                        .WithMany()
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MyloMail.Api.Domain.OutboxItem", b =>
                {
                    b.HasOne("MyloMail.Api.Domain.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyloMail.Api.Domain.SendIdentity", b =>
                {
                    b.HasOne("MyloMail.Api.Domain.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyloMail.Api.Domain.StagedChangeEvent", b =>
                {
                    b.HasOne("MyloMail.Api.Domain.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyloMail.Api.Domain.Mailbox", b =>
                {
                    b.Navigation("ImapMetadata");
                });

            modelBuilder.Entity("MyloMail.Api.Domain.Message", b =>
                {
                    b.Navigation("Occurrences");
                });

            modelBuilder.Entity("MyloMail.Api.Domain.MutationExecutionAttempt", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
