/* THIS (.ts) FILE IS GENERATED BY TypedSignalR.Client.TypeScript */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import type { HubConnection, IStreamResult, Subject } from '@microsoft/signalr';
import type { IMailHub, IMailClient } from './MyloMail.Api.Hubs';
import type { MailboxSummaryDto, MessageSummaryDto, MessageBodyDto, AttachmentDto, DraftDto, SaveDraftRequest, AccountCapabilitiesDto, AccountSettingsDto, CalendarSummaryDto, CalendarEventSummaryDto, SaveCalendarEventRequest, CalendarEventDetailDto, ExportJobDto, AccountDto, SyncProgressDto, MutationFailureDto, OutboxItemDto, NotificationDto } from '../MyloMail.Api.Contracts';
import type { PendingChangeDto } from '../MyloMail.Api.Hubs';
import type { InviteResponse } from '../MyloMail.Api.Domain';


// components

export type Disposable = {
    dispose(): void;
}

export type HubProxyFactory<T> = {
    createHubProxy(connection: HubConnection): T;
}

export type ReceiverRegister<T> = {
    register(connection: HubConnection, receiver: T): Disposable;
}

type ReceiverMethod = {
    methodName: string,
    method: (...args: any[]) => void
}

class ReceiverMethodSubscription implements Disposable {

    public constructor(
        private connection: HubConnection,
        private receiverMethod: ReceiverMethod[]) {
    }

    public readonly dispose = () => {
        for (const it of this.receiverMethod) {
            this.connection.off(it.methodName, it.method);
        }
    }
}

// API

export type HubProxyFactoryProvider = {
    (hubType: "IMailHub"): HubProxyFactory<IMailHub>;
}

export const getHubProxyFactory = ((hubType: string) => {
    if(hubType === "IMailHub") {
        return IMailHub_HubProxyFactory.Instance;
    }
}) as HubProxyFactoryProvider;

export type ReceiverRegisterProvider = {
    (receiverType: "IMailClient"): ReceiverRegister<IMailClient>;
}

export const getReceiverRegister = ((receiverType: string) => {
    if(receiverType === "IMailClient") {
        return IMailClient_Binder.Instance;
    }
}) as ReceiverRegisterProvider;

// HubProxy

class IMailHub_HubProxyFactory implements HubProxyFactory<IMailHub> {
    public static Instance = new IMailHub_HubProxyFactory();

    private constructor() {
    }

    public readonly createHubProxy = (connection: HubConnection): IMailHub => {
        return new IMailHub_HubProxy(connection);
    }
}

class IMailHub_HubProxy implements IMailHub {

    public constructor(private connection: HubConnection) {
    }

    public readonly getMailboxes = async (accountId: string): Promise<MailboxSummaryDto[]> => {
        return await this.connection.invoke("GetMailboxes", accountId);
    }

    public readonly getMessages = async (mailboxId: string, take: number): Promise<MessageSummaryDto[]> => {
        return await this.connection.invoke("GetMessages", mailboxId, take);
    }

    public readonly getPendingSyncState = async (accountId: string): Promise<PendingChangeDto[]> => {
        return await this.connection.invoke("GetPendingSyncState", accountId);
    }

    public readonly getMessageBody = async (messageId: string): Promise<MessageBodyDto> => {
        return await this.connection.invoke("GetMessageBody", messageId);
    }

    public readonly getAttachmentMetadata = async (messageId: string): Promise<AttachmentDto[]> => {
        return await this.connection.invoke("GetAttachmentMetadata", messageId);
    }

    public readonly search = async (accountId: string, query: string, mailboxId: (string | undefined)): Promise<MessageSummaryDto[]> => {
        return await this.connection.invoke("Search", accountId, query, mailboxId);
    }

    public readonly getDrafts = async (accountId: string): Promise<DraftDto[]> => {
        return await this.connection.invoke("GetDrafts", accountId);
    }

    public readonly saveDraft = async (request: SaveDraftRequest): Promise<DraftDto> => {
        return await this.connection.invoke("SaveDraft", request);
    }

    public readonly deleteDraft = async (draftId: string): Promise<void> => {
        return await this.connection.invoke("DeleteDraft", draftId);
    }

    public readonly sendDraft = async (draftId: string): Promise<string> => {
        return await this.connection.invoke("SendDraft", draftId);
    }

    public readonly cancelScheduledSend = async (outboxItemId: string): Promise<boolean> => {
        return await this.connection.invoke("CancelScheduledSend", outboxItemId);
    }

    public readonly createMailbox = async (accountId: string, name: string, parentId: (string | undefined)): Promise<void> => {
        return await this.connection.invoke("CreateMailbox", accountId, name, parentId);
    }

    public readonly renameMailbox = async (mailboxId: string, newName: string): Promise<void> => {
        return await this.connection.invoke("RenameMailbox", mailboxId, newName);
    }

    public readonly deleteMailbox = async (mailboxId: string): Promise<boolean> => {
        return await this.connection.invoke("DeleteMailbox", mailboxId);
    }

    public readonly moveMailbox = async (mailboxId: string, newParentId: (string | undefined)): Promise<void> => {
        return await this.connection.invoke("MoveMailbox", mailboxId, newParentId);
    }

    public readonly reorderMailboxes = async (accountId: string, parentId: (string | undefined), orderedMailboxIds: string[]): Promise<void> => {
        return await this.connection.invoke("ReorderMailboxes", accountId, parentId, orderedMailboxIds);
    }

    public readonly setMailboxCollapsed = async (mailboxId: string, collapsed: boolean): Promise<void> => {
        return await this.connection.invoke("SetMailboxCollapsed", mailboxId, collapsed);
    }

    public readonly getAccountCapabilities = async (accountId: string): Promise<AccountCapabilitiesDto> => {
        return await this.connection.invoke("GetAccountCapabilities", accountId);
    }

    public readonly updateAccount = async (settings: AccountSettingsDto): Promise<AccountSettingsDto> => {
        return await this.connection.invoke("UpdateAccount", settings);
    }

    public readonly reorderAccounts = async (orderedAccountIds: string[]): Promise<void> => {
        return await this.connection.invoke("ReorderAccounts", orderedAccountIds);
    }

    public readonly setAccountSidebarCollapsed = async (accountId: string, collapsed: boolean): Promise<void> => {
        return await this.connection.invoke("SetAccountSidebarCollapsed", accountId, collapsed);
    }

    public readonly trustCertificate = async (accountId: string, hostname: string, sha256Fingerprint: string): Promise<void> => {
        return await this.connection.invoke("TrustCertificate", accountId, hostname, sha256Fingerprint);
    }

    public readonly setFlags = async (accountId: string, messageIds: string[], isRead: (boolean | undefined), isFlagged: (boolean | undefined)): Promise<void> => {
        return await this.connection.invoke("SetFlags", accountId, messageIds, isRead, isFlagged);
    }

    public readonly moveMessages = async (accountId: string, messageIds: string[], targetMailboxId: string): Promise<void> => {
        return await this.connection.invoke("MoveMessages", accountId, messageIds, targetMailboxId);
    }

    public readonly removeFromMailbox = async (accountId: string, messageIds: string[], mailboxId: string): Promise<void> => {
        return await this.connection.invoke("RemoveFromMailbox", accountId, messageIds, mailboxId);
    }

    public readonly moveToTrash = async (accountId: string, messageIds: string[]): Promise<void> => {
        return await this.connection.invoke("MoveToTrash", accountId, messageIds);
    }

    public readonly deletePermanently = async (accountId: string, messageIds: string[]): Promise<void> => {
        return await this.connection.invoke("DeletePermanently", accountId, messageIds);
    }

    public readonly getCalendars = async (accountId: string): Promise<CalendarSummaryDto[]> => {
        return await this.connection.invoke("GetCalendars", accountId);
    }

    public readonly getCalendarEvents = async (calendarId: string, from: (Date | string), to: (Date | string)): Promise<CalendarEventSummaryDto[]> => {
        return await this.connection.invoke("GetCalendarEvents", calendarId, from, to);
    }

    public readonly saveCalendarEvent = async (request: SaveCalendarEventRequest): Promise<CalendarEventSummaryDto> => {
        return await this.connection.invoke("SaveCalendarEvent", request);
    }

    public readonly deleteCalendarEvent = async (eventId: string): Promise<void> => {
        return await this.connection.invoke("DeleteCalendarEvent", eventId);
    }

    public readonly getCalendarEventDetail = async (eventId: string): Promise<CalendarEventDetailDto> => {
        return await this.connection.invoke("GetCalendarEventDetail", eventId);
    }

    public readonly respondToInvite = async (eventId: string, response: InviteResponse, comment: string): Promise<void> => {
        return await this.connection.invoke("RespondToInvite", eventId, response, comment);
    }

    public readonly markNotificationDelivered = async (notificationId: string): Promise<void> => {
        return await this.connection.invoke("MarkNotificationDelivered", notificationId);
    }

    public readonly resolveStagedMessage = async (notificationId: string): Promise<(string | undefined)> => {
        return await this.connection.invoke("ResolveStagedMessage", notificationId);
    }

    public readonly saveMessageAsEml = async (messageId: string): Promise<string> => {
        return await this.connection.invoke("SaveMessageAsEml", messageId);
    }

    public readonly startBulkExport = async (accountId: string, destinationPath: string): Promise<string> => {
        return await this.connection.invoke("StartBulkExport", accountId, destinationPath);
    }

    public readonly cancelBulkExport = async (exportId: string): Promise<void> => {
        return await this.connection.invoke("CancelBulkExport", exportId);
    }

    public readonly getExportStatus = async (accountId: string): Promise<ExportJobDto> => {
        return await this.connection.invoke("GetExportStatus", accountId);
    }
}


// Receiver

class IMailClient_Binder implements ReceiverRegister<IMailClient> {

    public static Instance = new IMailClient_Binder();

    private constructor() {
    }

    public readonly register = (connection: HubConnection, receiver: IMailClient): Disposable => {

        const __accountStatusChanged = (...args: [AccountDto]) => receiver.accountStatusChanged(...args);
        const __mailboxUpdated = (...args: [MailboxSummaryDto]) => receiver.mailboxUpdated(...args);
        const __mailboxTreeChanged = (...args: [string]) => receiver.mailboxTreeChanged(...args);
        const __messageReceived = (...args: [MessageSummaryDto]) => receiver.messageReceived(...args);
        const __messageUpdated = (...args: [MessageSummaryDto]) => receiver.messageUpdated(...args);
        const __messageDeleted = (...args: [string]) => receiver.messageDeleted(...args);
        const __syncProgress = (...args: [SyncProgressDto]) => receiver.syncProgress(...args);
        const __exportProgress = (...args: [string, number, number]) => receiver.exportProgress(...args);
        const __messageSyncFailed = (...args: [MutationFailureDto]) => receiver.messageSyncFailed(...args);
        const __draftUpdated = (...args: [string]) => receiver.draftUpdated(...args);
        const __outboxStatusChanged = (...args: [OutboxItemDto]) => receiver.outboxStatusChanged(...args);
        const __calendarEventUpdated = (...args: [string]) => receiver.calendarEventUpdated(...args);
        const __calendarConflictDetected = (...args: [string]) => receiver.calendarConflictDetected(...args);
        const __connectivityChanged = (...args: [boolean]) => receiver.connectivityChanged(...args);
        const __notificationReady = (...args: [NotificationDto]) => receiver.notificationReady(...args);

        connection.on("AccountStatusChanged", __accountStatusChanged);
        connection.on("MailboxUpdated", __mailboxUpdated);
        connection.on("MailboxTreeChanged", __mailboxTreeChanged);
        connection.on("MessageReceived", __messageReceived);
        connection.on("MessageUpdated", __messageUpdated);
        connection.on("MessageDeleted", __messageDeleted);
        connection.on("SyncProgress", __syncProgress);
        connection.on("ExportProgress", __exportProgress);
        connection.on("MessageSyncFailed", __messageSyncFailed);
        connection.on("DraftUpdated", __draftUpdated);
        connection.on("OutboxStatusChanged", __outboxStatusChanged);
        connection.on("CalendarEventUpdated", __calendarEventUpdated);
        connection.on("CalendarConflictDetected", __calendarConflictDetected);
        connection.on("ConnectivityChanged", __connectivityChanged);
        connection.on("NotificationReady", __notificationReady);

        const methodList: ReceiverMethod[] = [
            { methodName: "AccountStatusChanged", method: __accountStatusChanged },
            { methodName: "MailboxUpdated", method: __mailboxUpdated },
            { methodName: "MailboxTreeChanged", method: __mailboxTreeChanged },
            { methodName: "MessageReceived", method: __messageReceived },
            { methodName: "MessageUpdated", method: __messageUpdated },
            { methodName: "MessageDeleted", method: __messageDeleted },
            { methodName: "SyncProgress", method: __syncProgress },
            { methodName: "ExportProgress", method: __exportProgress },
            { methodName: "MessageSyncFailed", method: __messageSyncFailed },
            { methodName: "DraftUpdated", method: __draftUpdated },
            { methodName: "OutboxStatusChanged", method: __outboxStatusChanged },
            { methodName: "CalendarEventUpdated", method: __calendarEventUpdated },
            { methodName: "CalendarConflictDetected", method: __calendarConflictDetected },
            { methodName: "ConnectivityChanged", method: __connectivityChanged },
            { methodName: "NotificationReady", method: __notificationReady }
        ]

        return new ReceiverMethodSubscription(connection, methodList);
    }
}

