/* THIS (.ts) FILE IS GENERATED BY TypedSignalR.Client.TypeScript */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import type { IStreamResult, Subject } from '@microsoft/signalr';
import type { MailboxSummaryDto, MessageSummaryDto, MessageBodyDto, MessageInviteDto, AttachmentDto, AttachmentConstraintsDto, MessageReplyContextDto, DraftDto, SendIdentityDto, SaveDraftRequest, ContactDto, ContactSuggestionDto, SaveContactRequest, DeleteContactRequest, AccountCapabilitiesDto, AccountSettingsDto, CalendarSummaryDto, CalendarEventSummaryDto, SaveCalendarEventRequest, CalendarEventDetailDto, ExportJobDto, AccountDto, SyncProgressDto, MutationFailureDto, OutboxItemDto, NotificationDto } from '../MyloMail.Api.Contracts';
import type { PendingChangeDto } from '../MyloMail.Api.Hubs';
import type { InitialSyncMode, SpecialUse, InviteResponse } from '../MyloMail.Api.Domain';

/**
* The renderer's connection to the backend (§7).
*/
export type IMailHub = {
    /**
    * @param accountId Transpiled from System.Guid
    * @returns Transpiled from System.Threading.Tasks.Task<System.Collections.Generic.IReadOnlyList<MyloMail.Api.Contracts.MailboxSummaryDto>>
    */
    getMailboxes(accountId: string): Promise<MailboxSummaryDto[]>;
    /**
    * @param mailboxId Transpiled from System.Guid
    * @param skip Transpiled from int
    * @param take Transpiled from int
    * @returns Transpiled from System.Threading.Tasks.Task<System.Collections.Generic.IReadOnlyList<MyloMail.Api.Contracts.MessageSummaryDto>>
    */
    getMessages(mailboxId: string, skip: number, take: number): Promise<MessageSummaryDto[]>;
    /**
    * @param mailboxId Transpiled from System.Guid
    * @param threadId Transpiled from string
    * @returns Transpiled from System.Threading.Tasks.Task<System.Collections.Generic.IReadOnlyList<MyloMail.Api.Contracts.MessageSummaryDto>>
    */
    getThreadMessages(mailboxId: string, threadId: string): Promise<MessageSummaryDto[]>;
    /**
    * @param accountId Transpiled from System.Guid
    * @param mailboxId Transpiled from System.Guid
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    setActiveMailbox(accountId: string, mailboxId: string): Promise<void>;
    /**
    * @param accountId Transpiled from System.Guid
    * @returns Transpiled from System.Threading.Tasks.Task<System.Collections.Generic.IReadOnlyList<MyloMail.Api.Hubs.PendingChangeDto>>
    */
    getPendingSyncState(accountId: string): Promise<PendingChangeDto[]>;
    /**
    * @param messageId Transpiled from System.Guid
    * @returns Transpiled from System.Threading.Tasks.Task<MyloMail.Api.Contracts.MessageBodyDto>
    */
    getMessageBody(messageId: string): Promise<MessageBodyDto>;
    /**
    * The meeting invite this message carries, if any (§13 Epic 7) — null for an ordinary
    * message, and also null until the message's raw content has been fetched (this reads the
    * same stored bytes  derives its content from, not a live
    * re-fetch).
    * @param messageId Transpiled from System.Guid
    * @returns Transpiled from System.Threading.Tasks.Task<MyloMail.Api.Contracts.MessageInviteDto?>
    */
    getMessageInvite(messageId: string): Promise<MessageInviteDto>;
    /**
    * Applies a reply that could not be authenticated with DKIM/DMARC only after the user
    * explicitly accepts the spoofing risk shown in the reading pane.
    * @param messageId Transpiled from System.Guid
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    acceptUnverifiedInviteReply(messageId: string): Promise<void>;
    /**
    * @param messageId Transpiled from System.Guid
    * @returns Transpiled from System.Threading.Tasks.Task<System.Collections.Generic.IReadOnlyList<MyloMail.Api.Contracts.AttachmentDto>>
    */
    getAttachmentMetadata(messageId: string): Promise<AttachmentDto[]>;
    /**
    * The account's attachment limits (§15), for Compose to check before send. Reported
    * honestly rather than as a single number — see .
    * @param accountId Transpiled from System.Guid
    * @returns Transpiled from System.Threading.Tasks.Task<MyloMail.Api.Contracts.AttachmentConstraintsDto>
    */
    getAttachmentConstraints(accountId: string): Promise<AttachmentConstraintsDto>;
    /**
    * The connectivity-aware pause logic's current state (§7, §15), so a window opened while
    * already offline shows the calm banner immediately rather than waiting for the next
    * transition — ConnectivityChanged only fires on a change, not on connect.
    * @returns Transpiled from System.Threading.Tasks.Task<bool>
    */
    getConnectivity(): Promise<boolean>;
    /**
    * The address/subject/date fields a reply or forward is built from (§13).
    * @param messageId Transpiled from System.Guid
    * @returns Transpiled from System.Threading.Tasks.Task<MyloMail.Api.Contracts.MessageReplyContextDto>
    */
    getMessageReplyContext(messageId: string): Promise<MessageReplyContextDto>;
    /**
    * @param accountId Transpiled from System.Guid
    * @param query Transpiled from string
    * @param mailboxId Transpiled from System.Guid?
    * @returns Transpiled from System.Threading.Tasks.Task<System.Collections.Generic.IReadOnlyList<MyloMail.Api.Contracts.MessageSummaryDto>>
    */
    search(accountId: string, query: string, mailboxId: (string | undefined)): Promise<MessageSummaryDto[]>;
    /**
    * Structured drafts, including drafts discovered from the server's Drafts mailbox.
    * @param accountId Transpiled from System.Guid
    * @returns Transpiled from System.Threading.Tasks.Task<System.Collections.Generic.IReadOnlyList<MyloMail.Api.Contracts.DraftDto>>
    */
    getDrafts(accountId: string): Promise<DraftDto[]>;
    /**
    * This account's send-as identities, default first, for compose's identity picker (§1,
    * §15). Always at least one row — every account has a default identity.
    * @param accountId Transpiled from System.Guid
    * @returns Transpiled from System.Threading.Tasks.Task<System.Collections.Generic.IReadOnlyList<MyloMail.Api.Contracts.SendIdentityDto>>
    */
    getSendIdentities(accountId: string): Promise<SendIdentityDto[]>;
    /**
    * Adds a send-as identity — the account's first ever becomes its default (§1, §15).
    * @param accountId Transpiled from System.Guid
    * @param displayName Transpiled from string
    * @param emailAddress Transpiled from string
    * @param signatureHtml Transpiled from string?
    * @returns Transpiled from System.Threading.Tasks.Task<MyloMail.Api.Contracts.SendIdentityDto>
    */
    addSendIdentity(accountId: string, displayName: string, emailAddress: string, signatureHtml: string): Promise<SendIdentityDto>;
    /**
    * @param identityId Transpiled from System.Guid
    * @param displayName Transpiled from string
    * @param emailAddress Transpiled from string
    * @param signatureHtml Transpiled from string?
    * @returns Transpiled from System.Threading.Tasks.Task<MyloMail.Api.Contracts.SendIdentityDto>
    */
    updateSendIdentity(identityId: string, displayName: string, emailAddress: string, signatureHtml: string): Promise<SendIdentityDto>;
    /**
    * Promotes one identity to the account's default, demoting whichever one held it (§1).
    * @param identityId Transpiled from System.Guid
    * @returns Transpiled from System.Threading.Tasks.Task<MyloMail.Api.Contracts.SendIdentityDto>
    */
    setDefaultSendIdentity(identityId: string): Promise<SendIdentityDto>;
    /**
    * @param identityId Transpiled from System.Guid
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    deleteSendIdentity(identityId: string): Promise<void>;
    /**
    * @param request Transpiled from MyloMail.Api.Contracts.SaveDraftRequest
    * @returns Transpiled from System.Threading.Tasks.Task<MyloMail.Api.Contracts.DraftDto>
    */
    saveDraft(request: SaveDraftRequest): Promise<DraftDto>;
    /**
    * Resolves a draft flagged SyncConflict (§1, §15): the server's copy changed
    * while this one was being edited locally.  true keeps the
    * local version (abandoning the conflicting remote draft and pushing a fresh one); false
    * discards the local edit and pulls the server's actual current content instead.
    * @param draftId Transpiled from System.Guid
    * @param keepMine Transpiled from bool
    * @returns Transpiled from System.Threading.Tasks.Task<MyloMail.Api.Contracts.DraftDto>
    */
    resolveDraftConflict(draftId: string, keepMine: boolean): Promise<DraftDto>;
    /**
    * @param accountId Transpiled from System.Guid
    * @returns Transpiled from System.Threading.Tasks.Task<System.Collections.Generic.IReadOnlyList<MyloMail.Api.Contracts.ContactDto>>
    */
    getContacts(accountId: string): Promise<ContactDto[]>;
    /**
    * @param accountId Transpiled from System.Guid
    * @returns Transpiled from System.Threading.Tasks.Task<System.Collections.Generic.IReadOnlyList<MyloMail.Api.Contracts.ContactSuggestionDto>>
    */
    getContactSuggestions(accountId: string): Promise<ContactSuggestionDto[]>;
    /**
    * @param accountId Transpiled from System.Guid
    * @param query Transpiled from string
    * @returns Transpiled from System.Threading.Tasks.Task<System.Collections.Generic.IReadOnlyList<MyloMail.Api.Contracts.ContactDto>>
    */
    searchContacts(accountId: string, query: string): Promise<ContactDto[]>;
    /**
    * @param request Transpiled from MyloMail.Api.Contracts.SaveContactRequest
    * @returns Transpiled from System.Threading.Tasks.Task<MyloMail.Api.Contracts.ContactDto>
    */
    saveContact(request: SaveContactRequest): Promise<ContactDto>;
    /**
    * @param contactId Transpiled from System.Guid
    * @param keepMine Transpiled from bool
    * @returns Transpiled from System.Threading.Tasks.Task<MyloMail.Api.Contracts.ContactDto>
    */
    resolveContactConflict(contactId: string, keepMine: boolean): Promise<ContactDto>;
    /**
    * @param request Transpiled from MyloMail.Api.Contracts.DeleteContactRequest
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    deleteContact(request: DeleteContactRequest): Promise<void>;
    /**
    * @param contactId Transpiled from System.Guid
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    abandonAmbiguousContactCreate(contactId: string): Promise<void>;
    /**
    * @param draftId Transpiled from System.Guid
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    deleteDraft(draftId: string): Promise<void>;
    /**
    * Queues a draft for sending.  is null for a normal
    * send (the account's undo-send delay applies) or an explicit future time for a
    * scheduled send (§15) — both go through the same outbox mechanism.
    * @param draftId Transpiled from System.Guid
    * @param scheduledFor Transpiled from System.DateTimeOffset?
    * @returns Transpiled from System.Threading.Tasks.Task<System.Guid>
    */
    sendDraft(draftId: string, scheduledFor: ((Date | string) | undefined)): Promise<string>;
    /**
    * @param outboxItemId Transpiled from System.Guid
    * @returns Transpiled from System.Threading.Tasks.Task<bool>
    */
    cancelScheduledSend(outboxItemId: string): Promise<boolean>;
    /**
    * @param accountId Transpiled from System.Guid
    * @param name Transpiled from string
    * @param parentId Transpiled from System.Guid?
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    createMailbox(accountId: string, name: string, parentId: (string | undefined)): Promise<void>;
    /**
    * @param mailboxId Transpiled from System.Guid
    * @param newName Transpiled from string
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    renameMailbox(mailboxId: string, newName: string): Promise<void>;
    /**
    * @param mailboxId Transpiled from System.Guid
    * @returns Transpiled from System.Threading.Tasks.Task<bool>
    */
    deleteMailbox(mailboxId: string): Promise<boolean>;
    /**
    * Drag-a-folder-onto-a-folder reparenting (§13 Epic 2). Null moves it to the root.
    * @param mailboxId Transpiled from System.Guid
    * @param newParentId Transpiled from System.Guid?
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    moveMailbox(mailboxId: string, newParentId: (string | undefined)): Promise<void>;
    /**
    * Sidebar drag-reorder among siblings of one parent (§13 Epic 2) — purely local, since no
    * provider supports arbitrary folder ordering.
    * @param accountId Transpiled from System.Guid
    * @param parentId Transpiled from System.Guid?
    * @param orderedMailboxIds Transpiled from System.Collections.Generic.IReadOnlyList<System.Guid>
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    reorderMailboxes(accountId: string, parentId: (string | undefined), orderedMailboxIds: string[]): Promise<void>;
    /**
    * Sidebar expand/collapse for one folder, persisted across restarts (§13 Epic 2)
    * — purely local, the same as .
    * @param mailboxId Transpiled from System.Guid
    * @param collapsed Transpiled from bool
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    setMailboxCollapsed(mailboxId: string, collapsed: boolean): Promise<void>;
    /**
    * Bounds this one mailbox's initial sync differently from the account's own choice —
    * e.g. a large "All Mail" label discovered after account setup (§3, §13 Epic 3). Null
    * mode clears the override, reverting to the account's default. Only meaningful before
    * this mailbox's own backfill has started; the caller decides whether to offer it.
    * @param mailboxId Transpiled from System.Guid
    * @param mode Transpiled from MyloMail.Api.Domain.InitialSyncMode?
    * @param boundValue Transpiled from int?
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    setMailboxInitialSyncOverride(mailboxId: string, mode: (InitialSyncMode | undefined), boundValue: (number | undefined)): Promise<void>;
    /**
    * Corrects a mailbox's special-use role (Sent/Trash/Drafts/Archive/Junk) by hand — for a
    * server that doesn't advertise RFC 6154 SPECIAL-USE, whose folder names the provider's
    * own name-based fallback guessed wrong or didn't recognise (§13 Epic 2). Highest
    * precedence over both a real server attribute and the fallback guess; null clears it,
    * reverting to whatever the provider itself reports.
    * @param mailboxId Transpiled from System.Guid
    * @param specialUse Transpiled from MyloMail.Api.Domain.SpecialUse?
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    setMailboxSpecialUseOverride(mailboxId: string, specialUse: (SpecialUse | undefined)): Promise<void>;
    /**
    * @param accountId Transpiled from System.Guid
    * @returns Transpiled from System.Threading.Tasks.Task<MyloMail.Api.Contracts.AccountCapabilitiesDto>
    */
    getAccountCapabilities(accountId: string): Promise<AccountCapabilitiesDto>;
    /**
    * @param settings Transpiled from MyloMail.Api.Contracts.AccountSettingsDto
    * @returns Transpiled from System.Threading.Tasks.Task<MyloMail.Api.Contracts.AccountSettingsDto>
    */
    updateAccount(settings: AccountSettingsDto): Promise<AccountSettingsDto>;
    /**
    * Sidebar drag-reorder among accounts (§13 Epic 1) — purely local, the same as
    * : no provider has a concept of account ordering.
    * @param orderedAccountIds Transpiled from System.Collections.Generic.IReadOnlyList<System.Guid>
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    reorderAccounts(orderedAccountIds: string[]): Promise<void>;
    /**
    * Sidebar section expand/collapse for one account, persisted across restarts
    * (§13 Epic 2) — purely local, the same as .
    * @param accountId Transpiled from System.Guid
    * @param collapsed Transpiled from bool
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    setAccountSidebarCollapsed(accountId: string, collapsed: boolean): Promise<void>;
    /**
    * Pins a certificate for this account and hostname (§15) — offered only after normal TLS
    * validation has already failed and the user has seen the fingerprint/issuer this rejected
    * certificate presents; never called speculatively.
    * @param accountId Transpiled from System.Guid
    * @param hostname Transpiled from string
    * @param sha256Fingerprint Transpiled from string
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    trustCertificate(accountId: string, hostname: string, sha256Fingerprint: string): Promise<void>;
    /**
    * @param accountId Transpiled from System.Guid
    * @param messageIds Transpiled from System.Collections.Generic.IReadOnlyList<System.Guid>
    * @param isRead Transpiled from bool?
    * @param isFlagged Transpiled from bool?
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    setFlags(accountId: string, messageIds: string[], isRead: (boolean | undefined), isFlagged: (boolean | undefined)): Promise<void>;
    /**
    * @param accountId Transpiled from System.Guid
    * @param messageIds Transpiled from System.Collections.Generic.IReadOnlyList<System.Guid>
    * @param targetMailboxId Transpiled from System.Guid
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    moveMessages(accountId: string, messageIds: string[], targetMailboxId: string): Promise<void>;
    /**
    * Drops one membership without deleting the message (§6) — meaningful only where a
    * message can belong to several mailboxes at once, e.g. un-labelling in Gmail. Distinct
    * from : this never touches the message itself.
    * @param accountId Transpiled from System.Guid
    * @param messageIds Transpiled from System.Collections.Generic.IReadOnlyList<System.Guid>
    * @param mailboxId Transpiled from System.Guid
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    removeFromMailbox(accountId: string, messageIds: string[], mailboxId: string): Promise<void>;
    /**
    * @param accountId Transpiled from System.Guid
    * @param messageIds Transpiled from System.Collections.Generic.IReadOnlyList<System.Guid>
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    moveToTrash(accountId: string, messageIds: string[]): Promise<void>;
    /**
    * Deletes the message outright — never reversible by the app (§6).
    * @param accountId Transpiled from System.Guid
    * @param messageIds Transpiled from System.Collections.Generic.IReadOnlyList<System.Guid>
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    deletePermanently(accountId: string, messageIds: string[]): Promise<void>;
    /**
    * @param accountId Transpiled from System.Guid
    * @returns Transpiled from System.Threading.Tasks.Task<System.Collections.Generic.IReadOnlyList<MyloMail.Api.Contracts.CalendarSummaryDto>>
    */
    getCalendars(accountId: string): Promise<CalendarSummaryDto[]>;
    /**
    * @param calendarId Transpiled from System.Guid
    * @param from Transpiled from System.DateTimeOffset
    * @param to Transpiled from System.DateTimeOffset
    * @returns Transpiled from System.Threading.Tasks.Task<System.Collections.Generic.IReadOnlyList<MyloMail.Api.Contracts.CalendarEventSummaryDto>>
    */
    getCalendarEvents(calendarId: string, from: (Date | string), to: (Date | string)): Promise<CalendarEventSummaryDto[]>;
    /**
    * @param request Transpiled from MyloMail.Api.Contracts.SaveCalendarEventRequest
    * @returns Transpiled from System.Threading.Tasks.Task<MyloMail.Api.Contracts.CalendarEventSummaryDto>
    */
    saveCalendarEvent(request: SaveCalendarEventRequest): Promise<CalendarEventSummaryDto>;
    /**
    * @param eventId Transpiled from System.Guid
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    deleteCalendarEvent(eventId: string): Promise<void>;
    /**
    * Organiser, attendees and this account's own response, for the event detail
    * view (§13 Epic 7) — not carried on 's summary DTO.
    * @param eventId Transpiled from System.Guid
    * @returns Transpiled from System.Threading.Tasks.Task<MyloMail.Api.Contracts.CalendarEventDetailDto>
    */
    getCalendarEventDetail(eventId: string): Promise<CalendarEventDetailDto>;
    /**
    * Accept/Decline/Tentative on an invite (§13 Epic 7).
    * @param eventId Transpiled from System.Guid
    * @param response Transpiled from MyloMail.Api.Domain.InviteResponse
    * @param comment Transpiled from string?
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    respondToInvite(eventId: string, response: InviteResponse, comment: string): Promise<void>;
    /**
    * "Keep mine" ( true, force-overwrite the server) or "keep
    * theirs" (false, discard the local edit and pull the server's current version) for a
    * flagged calendar conflict (§15). A no-op if the event is not currently flagged.
    * @param eventId Transpiled from System.Guid
    * @param keepMine Transpiled from bool
    * @returns Transpiled from System.Threading.Tasks.Task<MyloMail.Api.Contracts.CalendarEventSummaryDto>
    */
    resolveEventConflict(eventId: string, keepMine: boolean): Promise<CalendarEventSummaryDto>;
    /**
    * Confirms the shell showed a notification at least once (§13 Epic 9).
    * @param notificationId Transpiled from System.Guid
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    markNotificationDelivered(notificationId: string): Promise<void>;
    /**
    * Fetches the message a still-staged notification points at, on demand, rather than the
    * navigation simply failing (§3). Null if the account's staged history still doesn't
    * resolve it — the caller only knows this notification was recorded, not why it might be
    * slow.
    * @param notificationId Transpiled from System.Guid
    * @returns Transpiled from System.Threading.Tasks.Task<System.Guid?>
    */
    resolveStagedMessage(notificationId: string): Promise<(string | undefined)>;
    /**
    * The raw MIME bytes for one message, base64-encoded, fetched on demand if needed.
    * @param messageId Transpiled from System.Guid
    * @returns Transpiled from System.Threading.Tasks.Task<string>
    */
    saveMessageAsEml(messageId: string): Promise<string>;
    /**
    * @param accountId Transpiled from System.Guid
    * @param destinationPath Transpiled from string
    * @returns Transpiled from System.Threading.Tasks.Task<System.Guid>
    */
    startBulkExport(accountId: string, destinationPath: string): Promise<string>;
    /**
    * @param exportId Transpiled from System.Guid
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    cancelBulkExport(exportId: string): Promise<void>;
    /**
    * The account's most recent export, if it has ever run one (§13 Export).
    * @param accountId Transpiled from System.Guid
    * @returns Transpiled from System.Threading.Tasks.Task<MyloMail.Api.Contracts.ExportJobDto?>
    */
    getExportStatus(accountId: string): Promise<ExportJobDto>;
}

/**
* Server-to-client events (§7).
*/
export type IMailClient = {
    /**
    * @param account Transpiled from MyloMail.Api.Contracts.AccountDto
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    accountStatusChanged(account: AccountDto): Promise<void>;
    /**
    * @param mailbox Transpiled from MyloMail.Api.Contracts.MailboxSummaryDto
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    mailboxUpdated(mailbox: MailboxSummaryDto): Promise<void>;
    /**
    * @param accountId Transpiled from System.Guid
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    mailboxTreeChanged(accountId: string): Promise<void>;
    /**
    * Steady-state sync only, never initial sync: notifying a user about a backlog
    * they already had is a flood, not news (§13, Epic 9).
    * @param message Transpiled from MyloMail.Api.Contracts.MessageSummaryDto
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    messageReceived(message: MessageSummaryDto): Promise<void>;
    /**
    * @param message Transpiled from MyloMail.Api.Contracts.MessageSummaryDto
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    messageUpdated(message: MessageSummaryDto): Promise<void>;
    /**
    * @param messageId Transpiled from System.Guid
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    messageDeleted(messageId: string): Promise<void>;
    /**
    * @param progress Transpiled from MyloMail.Api.Contracts.SyncProgressDto
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    syncProgress(progress: SyncProgressDto): Promise<void>;
    /**
    * @param exportId Transpiled from System.Guid
    * @param written Transpiled from int
    * @param total Transpiled from int
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    exportProgress(exportId: string, written: number, total: number): Promise<void>;
    /**
    * A mutation item reaching terminal failure (§6).
    * @param failure Transpiled from MyloMail.Api.Contracts.MutationFailureDto
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    messageSyncFailed(failure: MutationFailureDto): Promise<void>;
    /**
    * @param draftId Transpiled from System.Guid
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    draftUpdated(draftId: string): Promise<void>;
    /**
    * @param item Transpiled from MyloMail.Api.Contracts.OutboxItemDto
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    outboxStatusChanged(item: OutboxItemDto): Promise<void>;
    /**
    * @param eventId Transpiled from System.Guid
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    calendarEventUpdated(eventId: string): Promise<void>;
    /**
    * @param eventId Transpiled from System.Guid
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    calendarConflictDetected(eventId: string): Promise<void>;
    /**
    * @param accountId Transpiled from System.Guid
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    contactsChanged(accountId: string): Promise<void>;
    /**
    * Emitted when network-class failures begin and when connectivity returns, so the UI can
    * show one calm offline state rather than per-mailbox errors multiplying every poll (§15).
    * @param online Transpiled from bool
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    connectivityChanged(online: boolean): Promise<void>;
    /**
    * App-wide theme/close-behaviour/mailto-prompt state changed (§7, §13 Epic 10).
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    shellSettingsChanged(): Promise<void>;
    /**
    * The remote-content allow list changed (§7, §13 Epic 5, Epic 10).
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    trustedSendersChanged(): Promise<void>;
    /**
    * Relayed straight to the preload bridge, which asks electron-shell to show the
    * native OS notification. Dispatch is the shell's job, not the renderer's (§13 Epic 9).
    * @param notification Transpiled from MyloMail.Api.Contracts.NotificationDto
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    notificationReady(notification: NotificationDto): Promise<void>;
}

