/* THIS (.ts) FILE IS GENERATED BY TypedSignalR.Client.TypeScript */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import type { IStreamResult, Subject } from '@microsoft/signalr';
import type { MailboxSummaryDto, MessageSummaryDto, MessageBodyDto, AttachmentDto, DraftDto, SaveDraftRequest, AccountCapabilitiesDto, AccountSettingsDto, AccountDto, SyncProgressDto, MutationFailureDto, OutboxItemDto } from '../MyloMail.Api.Contracts';
import type { PendingChangeDto } from '../MyloMail.Api.Hubs';

/**
* The renderer's connection to the backend (§7).
*/
export type IMailHub = {
    /**
    * @param accountId Transpiled from System.Guid
    * @returns Transpiled from System.Threading.Tasks.Task<System.Collections.Generic.IReadOnlyList<MyloMail.Api.Contracts.MailboxSummaryDto>>
    */
    getMailboxes(accountId: string): Promise<MailboxSummaryDto[]>;
    /**
    * @param mailboxId Transpiled from System.Guid
    * @param take Transpiled from int
    * @returns Transpiled from System.Threading.Tasks.Task<System.Collections.Generic.IReadOnlyList<MyloMail.Api.Contracts.MessageSummaryDto>>
    */
    getMessages(mailboxId: string, take: number): Promise<MessageSummaryDto[]>;
    /**
    * @param accountId Transpiled from System.Guid
    * @returns Transpiled from System.Threading.Tasks.Task<System.Collections.Generic.IReadOnlyList<MyloMail.Api.Hubs.PendingChangeDto>>
    */
    getPendingSyncState(accountId: string): Promise<PendingChangeDto[]>;
    /**
    * @param messageId Transpiled from System.Guid
    * @returns Transpiled from System.Threading.Tasks.Task<MyloMail.Api.Contracts.MessageBodyDto>
    */
    getMessageBody(messageId: string): Promise<MessageBodyDto>;
    /**
    * @param messageId Transpiled from System.Guid
    * @returns Transpiled from System.Threading.Tasks.Task<System.Collections.Generic.IReadOnlyList<MyloMail.Api.Contracts.AttachmentDto>>
    */
    getAttachmentMetadata(messageId: string): Promise<AttachmentDto[]>;
    /**
    * @param accountId Transpiled from System.Guid
    * @param query Transpiled from string
    * @param mailboxId Transpiled from System.Guid?
    * @returns Transpiled from System.Threading.Tasks.Task<System.Collections.Generic.IReadOnlyList<MyloMail.Api.Contracts.MessageSummaryDto>>
    */
    search(accountId: string, query: string, mailboxId: (string | undefined)): Promise<MessageSummaryDto[]>;
    /**
    * Structured drafts, including drafts discovered from the server's Drafts mailbox.
    * @param accountId Transpiled from System.Guid
    * @returns Transpiled from System.Threading.Tasks.Task<System.Collections.Generic.IReadOnlyList<MyloMail.Api.Contracts.DraftDto>>
    */
    getDrafts(accountId: string): Promise<DraftDto[]>;
    /**
    * @param request Transpiled from MyloMail.Api.Contracts.SaveDraftRequest
    * @returns Transpiled from System.Threading.Tasks.Task<MyloMail.Api.Contracts.DraftDto>
    */
    saveDraft(request: SaveDraftRequest): Promise<DraftDto>;
    /**
    * @param draftId Transpiled from System.Guid
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    deleteDraft(draftId: string): Promise<void>;
    /**
    * @param draftId Transpiled from System.Guid
    * @returns Transpiled from System.Threading.Tasks.Task<System.Guid>
    */
    sendDraft(draftId: string): Promise<string>;
    /**
    * @param outboxItemId Transpiled from System.Guid
    * @returns Transpiled from System.Threading.Tasks.Task<bool>
    */
    cancelScheduledSend(outboxItemId: string): Promise<boolean>;
    /**
    * @param accountId Transpiled from System.Guid
    * @param name Transpiled from string
    * @param parentId Transpiled from System.Guid?
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    createMailbox(accountId: string, name: string, parentId: (string | undefined)): Promise<void>;
    /**
    * @param mailboxId Transpiled from System.Guid
    * @param newName Transpiled from string
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    renameMailbox(mailboxId: string, newName: string): Promise<void>;
    /**
    * @param mailboxId Transpiled from System.Guid
    * @returns Transpiled from System.Threading.Tasks.Task<bool>
    */
    deleteMailbox(mailboxId: string): Promise<boolean>;
    /**
    * @param accountId Transpiled from System.Guid
    * @returns Transpiled from System.Threading.Tasks.Task<MyloMail.Api.Contracts.AccountCapabilitiesDto>
    */
    getAccountCapabilities(accountId: string): Promise<AccountCapabilitiesDto>;
    /**
    * @param settings Transpiled from MyloMail.Api.Contracts.AccountSettingsDto
    * @returns Transpiled from System.Threading.Tasks.Task<MyloMail.Api.Contracts.AccountSettingsDto>
    */
    updateAccount(settings: AccountSettingsDto): Promise<AccountSettingsDto>;
    /**
    * @param accountId Transpiled from System.Guid
    * @param messageIds Transpiled from System.Collections.Generic.IReadOnlyList<System.Guid>
    * @param isRead Transpiled from bool?
    * @param isFlagged Transpiled from bool?
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    setFlags(accountId: string, messageIds: string[], isRead: (boolean | undefined), isFlagged: (boolean | undefined)): Promise<void>;
    /**
    * @param accountId Transpiled from System.Guid
    * @param messageIds Transpiled from System.Collections.Generic.IReadOnlyList<System.Guid>
    * @param targetMailboxId Transpiled from System.Guid
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    moveMessages(accountId: string, messageIds: string[], targetMailboxId: string): Promise<void>;
    /**
    * @param accountId Transpiled from System.Guid
    * @param messageIds Transpiled from System.Collections.Generic.IReadOnlyList<System.Guid>
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    moveToTrash(accountId: string, messageIds: string[]): Promise<void>;
}

/**
* Server-to-client events (§7).
*/
export type IMailClient = {
    /**
    * @param account Transpiled from MyloMail.Api.Contracts.AccountDto
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    accountStatusChanged(account: AccountDto): Promise<void>;
    /**
    * @param mailbox Transpiled from MyloMail.Api.Contracts.MailboxSummaryDto
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    mailboxUpdated(mailbox: MailboxSummaryDto): Promise<void>;
    /**
    * @param accountId Transpiled from System.Guid
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    mailboxTreeChanged(accountId: string): Promise<void>;
    /**
    * Steady-state sync only, never initial sync: notifying a user about a backlog
    * they already had is a flood, not news (§13, Epic 9).
    * @param message Transpiled from MyloMail.Api.Contracts.MessageSummaryDto
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    messageReceived(message: MessageSummaryDto): Promise<void>;
    /**
    * @param message Transpiled from MyloMail.Api.Contracts.MessageSummaryDto
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    messageUpdated(message: MessageSummaryDto): Promise<void>;
    /**
    * @param messageId Transpiled from System.Guid
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    messageDeleted(messageId: string): Promise<void>;
    /**
    * @param progress Transpiled from MyloMail.Api.Contracts.SyncProgressDto
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    syncProgress(progress: SyncProgressDto): Promise<void>;
    /**
    * @param exportId Transpiled from System.Guid
    * @param written Transpiled from int
    * @param total Transpiled from int
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    exportProgress(exportId: string, written: number, total: number): Promise<void>;
    /**
    * A mutation item reaching terminal failure (§6).
    * @param failure Transpiled from MyloMail.Api.Contracts.MutationFailureDto
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    messageSyncFailed(failure: MutationFailureDto): Promise<void>;
    /**
    * @param draftId Transpiled from System.Guid
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    draftUpdated(draftId: string): Promise<void>;
    /**
    * @param item Transpiled from MyloMail.Api.Contracts.OutboxItemDto
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    outboxStatusChanged(item: OutboxItemDto): Promise<void>;
    /**
    * @param eventId Transpiled from System.Guid
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    calendarEventUpdated(eventId: string): Promise<void>;
    /**
    * @param eventId Transpiled from System.Guid
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    calendarConflictDetected(eventId: string): Promise<void>;
    /**
    * Emitted when network-class failures begin and when connectivity returns, so the UI can
    * show one calm offline state rather than per-mailbox errors multiplying every poll (§15).
    * @param online Transpiled from bool
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    connectivityChanged(online: boolean): Promise<void>;
}

