/* THIS (.ts) FILE IS GENERATED BY Tapper */
/* eslint-disable */
/* tslint:disable */

/** Transpiled from MyloMail.Api.Domain.Address */
export type Address = {
    /** Transpiled from string? */
    name?: string;
    /** Transpiled from string */
    email: string;
}

/** Transpiled from MyloMail.Api.Domain.EventStatus */
export enum EventStatus {
    Confirmed = 0,
    Tentative = 1,
    Cancelled = 2,
}

/** Transpiled from MyloMail.Api.Domain.InviteResponse */
export enum InviteResponse {
    Accept = 0,
    Decline = 1,
    Tentative = 2,
}

/** Transpiled from MyloMail.Api.Domain.ProviderType */
export enum ProviderType {
    Imap = 0,
    Gmail = 1,
    Microsoft365 = 2,
}

/** Transpiled from MyloMail.Api.Domain.AuthState */
export enum AuthState {
    Connected = 0,
    NeedsReauth = 1,
    Error = 2,
}

/** Transpiled from MyloMail.Api.Domain.SpecialUse */
export enum SpecialUse {
    None = 0,
    Inbox = 1,
    Sent = 2,
    Drafts = 3,
    Trash = 4,
    Junk = 5,
    Archive = 6,
}

/** Transpiled from MyloMail.Api.Domain.InitialSyncMode */
export enum InitialSyncMode {
    LastNMonths = 0,
    LastNMessages = 1,
    Full = 2,
}

/** Transpiled from MyloMail.Api.Domain.CertificateTrustMode */
export enum CertificateTrustMode {
    Default = 0,
    TrustAll = 1,
}

/** Transpiled from MyloMail.Api.Domain.ExportJobStatus */
export enum ExportJobStatus {
    Running = 0,
    CancelRequested = 1,
    Cancelled = 2,
    Completed = 3,
    Failed = 4,
}

/** Transpiled from MyloMail.Api.Domain.MessageFlagField */
export enum MessageFlagField {
    IsRead = 0,
    IsFlagged = 1,
}

/** Transpiled from MyloMail.Api.Domain.NotificationKind */
export enum NotificationKind {
    NewMessage = 0,
}

/** Transpiled from MyloMail.Api.Domain.OutboxStatus */
export enum OutboxStatus {
    Draft = 0,
    Scheduled = 1,
    Pending = 2,
    Sending = 3,
    Sent = 4,
    Failed = 5,
    AmbiguousOutcome = 6,
    Cancelled = 7,
}

/** Transpiled from MyloMail.Api.Domain.CoverageStatus */
export enum CoverageStatus {
    NotStarted = 0,
    Backfilling = 1,
    Covered = 2,
    Failed = 3,
}

