/* THIS (.ts) FILE IS GENERATED BY Tapper */
/* eslint-disable */
/* tslint:disable */
import type { ProviderType, AuthState, SpecialUse, CoverageStatus, Address, OutboxStatus } from './MyloMail.Api.Domain';

/** Transpiled from MyloMail.Api.Contracts.AccountDto */
export type AccountDto = {
    /** Transpiled from System.Guid */
    id: string;
    /** Transpiled from string */
    displayName: string;
    /** Transpiled from string */
    emailAddress: string;
    /** Transpiled from MyloMail.Api.Domain.ProviderType */
    providerType: ProviderType;
    /** Transpiled from MyloMail.Api.Domain.AuthState */
    authState: AuthState;
    /** Transpiled from bool */
    isEnabled: boolean;
    /** Transpiled from string? */
    lastAuthError?: string;
    /** Transpiled from string */
    color: string;
    /** Transpiled from int */
    sortOrder: number;
}

/** Transpiled from MyloMail.Api.Contracts.AddAccountRequest */
export type AddAccountRequest = {
    /** Transpiled from string */
    displayName: string;
    /** Transpiled from MyloMail.Api.Domain.ProviderType */
    providerType: ProviderType;
    /** Transpiled from string */
    emailAddress: string;
    /** Transpiled from string? */
    secret?: string;
    /** Transpiled from MyloMail.Api.Contracts.ImapAccountSettings? */
    imap?: ImapAccountSettings;
}

/** Transpiled from MyloMail.Api.Contracts.ImapAccountSettings */
export type ImapAccountSettings = {
    /** Transpiled from string */
    host: string;
    /** Transpiled from int */
    port: number;
    /** Transpiled from bool */
    useSsl: boolean;
    /** Transpiled from string */
    userName: string;
    /** Transpiled from string */
    smtpHost: string;
    /** Transpiled from int */
    smtpPort: number;
}

/** Transpiled from MyloMail.Api.Contracts.HealthDto */
export type HealthDto = {
    /** Transpiled from string */
    status: string;
}

/** Transpiled from MyloMail.Api.Contracts.MailboxSummaryDto */
export type MailboxSummaryDto = {
    /** Transpiled from System.Guid */
    id: string;
    /** Transpiled from System.Guid */
    accountId: string;
    /** Transpiled from System.Guid */
    parentId?: string;
    /** Transpiled from string */
    name: string;
    /** Transpiled from MyloMail.Api.Domain.SpecialUse */
    specialUse: SpecialUse;
    /** Transpiled from int */
    providerTotalCount?: number;
    /** Transpiled from int */
    providerUnreadCount?: number;
    /** Transpiled from int */
    localCount: number;
    /** Transpiled from MyloMail.Api.Domain.CoverageStatus */
    coverage: CoverageStatus;
}

/** Transpiled from MyloMail.Api.Contracts.MessageSummaryDto */
export type MessageSummaryDto = {
    /** Transpiled from System.Guid */
    id: string;
    /** Transpiled from System.Guid */
    accountId: string;
    /** Transpiled from string */
    subject: string;
    /** Transpiled from string */
    snippet: string;
    /** Transpiled from System.Collections.Generic.IReadOnlyList<MyloMail.Api.Domain.Address> */
    from: Address[];
    /** Transpiled from System.DateTimeOffset */
    receivedAt: (Date | string);
    /** Transpiled from bool */
    isRead: boolean;
    /** Transpiled from bool */
    isFlagged: boolean;
    /** Transpiled from bool */
    hasNonInlineAttachments: boolean;
}

/** Transpiled from MyloMail.Api.Contracts.SyncProgressDto */
export type SyncProgressDto = {
    /** Transpiled from System.Guid */
    mailboxId: string;
    /** Transpiled from MyloMail.Api.Domain.CoverageStatus */
    status: CoverageStatus;
    /** Transpiled from int */
    messagesFetched: number;
    /** Transpiled from int */
    estimatedTotal?: number;
}

/** Transpiled from MyloMail.Api.Contracts.OutboxItemDto */
export type OutboxItemDto = {
    /** Transpiled from System.Guid */
    id: string;
    /** Transpiled from System.Guid */
    accountId: string;
    /** Transpiled from MyloMail.Api.Domain.OutboxStatus */
    status: OutboxStatus;
    /** Transpiled from System.DateTimeOffset */
    scheduledSendAt: (Date | string);
    /** Transpiled from string? */
    lastError?: string;
}

