/* THIS (.ts) FILE IS GENERATED BY Tapper */
/* eslint-disable */
/* tslint:disable */
import type { ProviderType, AuthState, CertificateTrustMode, InitialSyncMode, ExportJobStatus, SpecialUse, CoverageStatus, Address, OutboxStatus, EventStatus, AttendeeRole, ResponseStatus, InviteResponse } from './MyloMail.Api.Domain';
import type { ErrorCategory } from './MyloMail.Api.Errors';

/** Transpiled from MyloMail.Api.Contracts.AccountDto */
export type AccountDto = {
    /** Transpiled from System.Guid */
    id: string;
    /** Transpiled from string */
    displayName: string;
    /** Transpiled from string */
    emailAddress: string;
    /** Transpiled from MyloMail.Api.Domain.ProviderType */
    providerType: ProviderType;
    /** Transpiled from MyloMail.Api.Domain.AuthState */
    authState: AuthState;
    /** Transpiled from bool */
    isEnabled: boolean;
    /** Transpiled from string? */
    lastAuthError?: string;
    /** Transpiled from string */
    color: string;
    /** Transpiled from int */
    sortOrder: number;
    /** Transpiled from bool */
    sidebarCollapsed: boolean;
    /** Transpiled from int */
    pollIntervalSeconds: number;
    /** Transpiled from bool */
    pollingEnabled: boolean;
    /** Transpiled from int */
    undoSendDelaySeconds: number;
    /** Transpiled from bool */
    notificationsEnabled: boolean;
    /** Transpiled from MyloMail.Api.Domain.CertificateTrustMode */
    certificateTrustMode: CertificateTrustMode;
    /** Transpiled from int */
    attachmentSizeLimitOverride?: number;
}

/** Transpiled from MyloMail.Api.Contracts.AddAccountRequest */
export type AddAccountRequest = {
    /** Transpiled from string */
    displayName: string;
    /** Transpiled from MyloMail.Api.Domain.ProviderType */
    providerType: ProviderType;
    /** Transpiled from string */
    emailAddress: string;
    /** Transpiled from string? */
    secret?: string;
    /** Transpiled from MyloMail.Api.Contracts.ImapAccountSettings? */
    imap?: ImapAccountSettings;
    /** Transpiled from MyloMail.Api.Contracts.CalDavAccountSettings? */
    calDav?: CalDavAccountSettings;
    /** Transpiled from MyloMail.Api.Domain.CertificateTrustMode */
    certificateTrustMode: CertificateTrustMode;
    /** Transpiled from MyloMail.Api.Domain.InitialSyncMode */
    initialSyncMode: InitialSyncMode;
    /** Transpiled from int */
    initialSyncBoundValue?: number;
}

/** Transpiled from MyloMail.Api.Contracts.ReauthenticateAccountRequest */
export type ReauthenticateAccountRequest = {
    /** Transpiled from string? */
    secret?: string;
}

/** Transpiled from MyloMail.Api.Contracts.ImapAccountSettings */
export type ImapAccountSettings = {
    /** Transpiled from string */
    host: string;
    /** Transpiled from int */
    port: number;
    /** Transpiled from bool */
    useSsl: boolean;
    /** Transpiled from string */
    userName: string;
    /** Transpiled from string */
    smtpHost: string;
    /** Transpiled from int */
    smtpPort: number;
    /** Transpiled from bool */
    reuseImapCredentialForSmtp: boolean;
    /** Transpiled from string? */
    smtpSecret?: string;
    /** Transpiled from string? */
    smtpUserName?: string;
}

/** Transpiled from MyloMail.Api.Contracts.CalDavAccountSettings */
export type CalDavAccountSettings = {
    /** Transpiled from string */
    endpoint: string;
    /** Transpiled from string */
    userName: string;
    /** Transpiled from bool */
    reuseImapCredential: boolean;
    /** Transpiled from string? */
    secret?: string;
}

/** Transpiled from MyloMail.Api.Contracts.ExportJobDto */
export type ExportJobDto = {
    /** Transpiled from System.Guid */
    id: string;
    /** Transpiled from MyloMail.Api.Domain.ExportJobStatus */
    status: ExportJobStatus;
    /** Transpiled from int */
    writtenCount: number;
    /** Transpiled from int */
    totalCount: number;
    /** Transpiled from string? */
    lastError?: string;
}

/** Transpiled from MyloMail.Api.Contracts.HealthDto */
export type HealthDto = {
    /** Transpiled from string */
    status: string;
}

/** Transpiled from MyloMail.Api.Contracts.MailboxSummaryDto */
export type MailboxSummaryDto = {
    /** Transpiled from System.Guid */
    id: string;
    /** Transpiled from System.Guid */
    accountId: string;
    /** Transpiled from System.Guid */
    parentId?: string;
    /** Transpiled from string */
    name: string;
    /** Transpiled from MyloMail.Api.Domain.SpecialUse */
    specialUse: SpecialUse;
    /** Transpiled from int */
    providerTotalCount?: number;
    /** Transpiled from int */
    providerUnreadCount?: number;
    /** Transpiled from int */
    localCount: number;
    /** Transpiled from MyloMail.Api.Domain.CoverageStatus */
    coverage: CoverageStatus;
    /** Transpiled from bool */
    isCollapsed: boolean;
    /** Transpiled from MyloMail.Api.Domain.InitialSyncMode */
    initialSyncModeOverride?: InitialSyncMode;
    /** Transpiled from int */
    initialSyncBoundValueOverride?: number;
    /** Transpiled from bool */
    isSynthesized: boolean;
    /** Transpiled from MyloMail.Api.Domain.SpecialUse */
    specialUseOverride?: SpecialUse;
}

/** Transpiled from MyloMail.Api.Contracts.MessageSummaryDto */
export type MessageSummaryDto = {
    /** Transpiled from System.Guid */
    id: string;
    /** Transpiled from System.Guid */
    accountId: string;
    /** Transpiled from string */
    subject: string;
    /** Transpiled from string */
    snippet: string;
    /** Transpiled from System.Collections.Generic.IReadOnlyList<MyloMail.Api.Domain.Address> */
    from: Address[];
    /** Transpiled from System.DateTimeOffset */
    receivedAt: (Date | string);
    /** Transpiled from bool */
    isRead: boolean;
    /** Transpiled from bool */
    isFlagged: boolean;
    /** Transpiled from bool */
    hasNonInlineAttachments: boolean;
    /** Transpiled from MyloMail.Api.Errors.ErrorCategory */
    mutationFailure?: ErrorCategory;
    /** Transpiled from string? */
    searchSnippet?: string;
}

/** Transpiled from MyloMail.Api.Contracts.SyncProgressDto */
export type SyncProgressDto = {
    /** Transpiled from System.Guid */
    mailboxId: string;
    /** Transpiled from MyloMail.Api.Domain.CoverageStatus */
    status: CoverageStatus;
    /** Transpiled from int */
    messagesFetched: number;
    /** Transpiled from int */
    estimatedTotal?: number;
}

/** Transpiled from MyloMail.Api.Contracts.MessageBodyDto */
export type MessageBodyDto = {
    /** Transpiled from System.Guid */
    messageId: string;
    /** Transpiled from string? */
    text?: string;
    /** Transpiled from string? */
    html?: string;
    /** Transpiled from bool */
    isFetched: boolean;
    /** Transpiled from bool */
    isFailed: boolean;
}

/** Transpiled from MyloMail.Api.Contracts.AttachmentDto */
export type AttachmentDto = {
    /** Transpiled from System.Guid */
    id: string;
    /** Transpiled from System.Guid */
    messageId: string;
    /** Transpiled from string */
    filename: string;
    /** Transpiled from string */
    mimeType: string;
    /** Transpiled from long */
    size: number;
    /** Transpiled from bool */
    isInline: boolean;
}

/** Transpiled from MyloMail.Api.Contracts.MessageReplyContextDto */
export type MessageReplyContextDto = {
    /** Transpiled from System.Guid */
    messageId: string;
    /** Transpiled from System.Collections.Generic.IReadOnlyList<MyloMail.Api.Domain.Address> */
    from: Address[];
    /** Transpiled from System.Collections.Generic.IReadOnlyList<MyloMail.Api.Domain.Address> */
    to: Address[];
    /** Transpiled from System.Collections.Generic.IReadOnlyList<MyloMail.Api.Domain.Address> */
    cc: Address[];
    /** Transpiled from System.Collections.Generic.IReadOnlyList<MyloMail.Api.Domain.Address> */
    replyTo: Address[];
    /** Transpiled from string */
    subject: string;
    /** Transpiled from System.DateTimeOffset */
    receivedAt: (Date | string);
}

/** Transpiled from MyloMail.Api.Contracts.DraftDto */
export type DraftDto = {
    /** Transpiled from System.Guid */
    id: string;
    /** Transpiled from System.Guid */
    accountId: string;
    /** Transpiled from System.Guid */
    sendIdentityId: string;
    /** Transpiled from System.Guid */
    inReplyToMessageId?: string;
    /** Transpiled from System.Collections.Generic.IReadOnlyList<MyloMail.Api.Domain.Address> */
    to: Address[];
    /** Transpiled from System.Collections.Generic.IReadOnlyList<MyloMail.Api.Domain.Address> */
    cc: Address[];
    /** Transpiled from System.Collections.Generic.IReadOnlyList<MyloMail.Api.Domain.Address> */
    bcc: Address[];
    /** Transpiled from string */
    subject: string;
    /** Transpiled from string */
    bodyHtml: string;
    /** Transpiled from System.Collections.Generic.IReadOnlyList<MyloMail.Api.Contracts.DraftAttachmentDto> */
    attachments: DraftAttachmentDto[];
    /** Transpiled from bool */
    syncConflict: boolean;
}

/** Transpiled from MyloMail.Api.Contracts.DraftAttachmentDto */
export type DraftAttachmentDto = {
    /** Transpiled from System.Guid */
    id: string;
    /** Transpiled from string */
    filename: string;
    /** Transpiled from string */
    mimeType: string;
    /** Transpiled from long */
    size: number;
    /** Transpiled from bool */
    isInline: boolean;
}

/** Transpiled from MyloMail.Api.Contracts.SaveDraftRequest */
export type SaveDraftRequest = {
    /** Transpiled from System.Guid */
    draftId?: string;
    /** Transpiled from System.Guid */
    accountId: string;
    /** Transpiled from System.Guid */
    sendIdentityId?: string;
    /** Transpiled from System.Guid */
    inReplyToMessageId?: string;
    /** Transpiled from System.Collections.Generic.IReadOnlyList<MyloMail.Api.Domain.Address> */
    to: Address[];
    /** Transpiled from System.Collections.Generic.IReadOnlyList<MyloMail.Api.Domain.Address> */
    cc: Address[];
    /** Transpiled from System.Collections.Generic.IReadOnlyList<MyloMail.Api.Domain.Address> */
    bcc: Address[];
    /** Transpiled from string */
    subject: string;
    /** Transpiled from string */
    bodyHtml: string;
}

/** Transpiled from MyloMail.Api.Contracts.SendIdentityDto */
export type SendIdentityDto = {
    /** Transpiled from System.Guid */
    id: string;
    /** Transpiled from System.Guid */
    accountId: string;
    /** Transpiled from string */
    displayName: string;
    /** Transpiled from string */
    emailAddress: string;
    /** Transpiled from string? */
    signatureHtml?: string;
    /** Transpiled from bool */
    isDefault: boolean;
}

/** Transpiled from MyloMail.Api.Contracts.AccountCapabilitiesDto */
export type AccountCapabilitiesDto = {
    /** Transpiled from System.Guid */
    accountId: string;
    /** Transpiled from bool */
    deletingMailboxDeletesMessages: boolean;
}

/** Transpiled from MyloMail.Api.Contracts.AccountSettingsDto */
export type AccountSettingsDto = {
    /** Transpiled from System.Guid */
    id: string;
    /** Transpiled from string */
    displayName: string;
    /** Transpiled from string */
    color: string;
    /** Transpiled from int */
    pollIntervalSeconds: number;
    /** Transpiled from bool */
    pollingEnabled: boolean;
    /** Transpiled from int */
    undoSendDelaySeconds: number;
    /** Transpiled from bool */
    notificationsEnabled: boolean;
    /** Transpiled from MyloMail.Api.Domain.CertificateTrustMode */
    certificateTrustMode: CertificateTrustMode;
    /** Transpiled from int */
    attachmentSizeLimitOverride?: number;
}

/** Transpiled from MyloMail.Api.Contracts.MutationFailureDto */
export type MutationFailureDto = {
    /** Transpiled from System.Guid */
    messageId: string;
    /** Transpiled from MyloMail.Api.Errors.ErrorCategory */
    category: ErrorCategory;
    /** Transpiled from string? */
    detail?: string;
}

/** Transpiled from MyloMail.Api.Contracts.OutboxItemDto */
export type OutboxItemDto = {
    /** Transpiled from System.Guid */
    id: string;
    /** Transpiled from System.Guid */
    accountId: string;
    /** Transpiled from MyloMail.Api.Domain.OutboxStatus */
    status: OutboxStatus;
    /** Transpiled from System.DateTimeOffset */
    scheduledSendAt: (Date | string);
    /** Transpiled from string? */
    lastError?: string;
    /** Transpiled from System.DateTimeOffset */
    reconcilingSince?: (Date | string);
}

/** Transpiled from MyloMail.Api.Contracts.CalendarSummaryDto */
export type CalendarSummaryDto = {
    /** Transpiled from System.Guid */
    id: string;
    /** Transpiled from System.Guid */
    accountId: string;
    /** Transpiled from string */
    name: string;
    /** Transpiled from string? */
    colour?: string;
    /** Transpiled from bool */
    isDefault: boolean;
}

/** Transpiled from MyloMail.Api.Contracts.CalendarEventSummaryDto */
export type CalendarEventSummaryDto = {
    /** Transpiled from System.Guid */
    id: string;
    /** Transpiled from System.Guid */
    calendarId: string;
    /** Transpiled from string */
    title: string;
    /** Transpiled from string? */
    location?: string;
    /** Transpiled from string? */
    description?: string;
    /** Transpiled from System.DateTimeOffset */
    start: (Date | string);
    /** Transpiled from System.DateTimeOffset */
    end: (Date | string);
    /** Transpiled from bool */
    isAllDay: boolean;
    /** Transpiled from MyloMail.Api.Domain.EventStatus */
    status: EventStatus;
    /** Transpiled from bool */
    isRecurring: boolean;
    /** Transpiled from bool */
    syncConflict: boolean;
    /** Transpiled from bool */
    isVirtualOccurrence: boolean;
    /** Transpiled from System.Guid */
    masterEventId?: string;
}

/** Transpiled from MyloMail.Api.Contracts.AttendeeDto */
export type AttendeeDto = {
    /** Transpiled from string? */
    name?: string;
    /** Transpiled from string */
    email: string;
    /** Transpiled from MyloMail.Api.Domain.AttendeeRole */
    role: AttendeeRole;
    /** Transpiled from MyloMail.Api.Domain.ResponseStatus */
    responseStatus: ResponseStatus;
}

/** Transpiled from MyloMail.Api.Contracts.CalendarEventDetailDto */
export type CalendarEventDetailDto = {
    /** Transpiled from System.Guid */
    id: string;
    /** Transpiled from MyloMail.Api.Domain.Address? */
    organizer?: Address;
    /** Transpiled from System.Collections.Generic.IReadOnlyList<MyloMail.Api.Contracts.AttendeeDto> */
    attendees: AttendeeDto[];
    /** Transpiled from bool */
    isOrganizer: boolean;
    /** Transpiled from MyloMail.Api.Domain.InviteResponse */
    myResponseStatus?: InviteResponse;
    /** Transpiled from System.Collections.Generic.IReadOnlyList<System.DateTimeOffset> */
    reminders: (Date | string)[];
}

/** Transpiled from MyloMail.Api.Contracts.MessageInviteDto */
export type MessageInviteDto = {
    /** Transpiled from System.Guid */
    eventId?: string;
    /** Transpiled from string */
    title: string;
    /** Transpiled from System.DateTimeOffset */
    start: (Date | string);
    /** Transpiled from System.DateTimeOffset */
    end: (Date | string);
    /** Transpiled from MyloMail.Api.Domain.Address? */
    organizer?: Address;
    /** Transpiled from MyloMail.Api.Domain.InviteResponse */
    myResponseStatus?: InviteResponse;
}

/** Transpiled from MyloMail.Api.Contracts.AttachmentConstraintsDto */
export type AttachmentConstraintsDto = {
    /** Transpiled from long */
    apiPerFileLimit?: number;
    /** Transpiled from long */
    knownMessageSizeLimit?: number;
    /** Transpiled from long */
    configuredOverride?: number;
    /** Transpiled from bool */
    isUnknown: boolean;
}

/** Transpiled from MyloMail.Api.Contracts.NotificationDto */
export type NotificationDto = {
    /** Transpiled from System.Guid */
    id: string;
    /** Transpiled from System.Guid */
    accountId: string;
    /** Transpiled from System.Guid */
    messageId?: string;
    /** Transpiled from string */
    title: string;
    /** Transpiled from string */
    body: string;
}

/** Transpiled from MyloMail.Api.Contracts.SaveCalendarEventRequest */
export type SaveCalendarEventRequest = {
    /** Transpiled from System.Guid */
    eventId?: string;
    /** Transpiled from System.Guid */
    calendarId: string;
    /** Transpiled from string */
    title: string;
    /** Transpiled from string? */
    location?: string;
    /** Transpiled from string? */
    description?: string;
    /** Transpiled from System.DateTimeOffset */
    start: (Date | string);
    /** Transpiled from System.DateTimeOffset */
    end: (Date | string);
    /** Transpiled from bool */
    isAllDay: boolean;
}

