/* THIS (.ts) FILE IS GENERATED BY Tapper */
/* eslint-disable */
/* tslint:disable */
import type { MessageFlagField } from './MyloMail.Api.Domain';

/** Transpiled from MyloMail.Api.Hubs.PendingChangeDto */
export type PendingChangeDto = {
    /** Transpiled from System.Guid */
    messageId: string;
    /** Transpiled from MyloMail.Api.Domain.MessageFlagField */
    field: MessageFlagField;
    /** Transpiled from bool */
    desiredValue: boolean;
}

