/* THIS (.ts) FILE IS GENERATED BY Tapper */
/* eslint-disable */
/* tslint:disable */

/** Transpiled from MyloMail.Api.Errors.ErrorCategory */
export enum ErrorCategory {
    Network = 0,
    Auth = 1,
    RateLimit = 2,
    Validation = 3,
    ProviderRejected = 4,
    Conflict = 5,
    Unknown = 6,
}

