/*
 * This source code was auto-generated by TypeContractor.
 * Changes to this file may cause incorrect behavior and will be lost when the
 * code is regenerated next time TypeContractor runs.
 */
import { z } from 'zod';

export enum AuthState {
  Connected = 0,
  NeedsReauth = 1,
  Error = 2,
  CredentialStoreUnavailable = 3,
}

export const AuthStateEnum = z.enum(["Connected", "NeedsReauth", "Error", "CredentialStoreUnavailable"]);
export type AuthStateEnumType = z.infer<typeof AuthStateEnum>;
