/*
 * This source code was auto-generated by TypeContractor.
 * Changes to this file may cause incorrect behavior and will be lost when the
 * code is regenerated next time TypeContractor runs.
 */
import { z } from 'zod';

export enum CertificateTrustMode {
  Default = 0,
  TrustAll = 1,
}

export const CertificateTrustModeEnum = z.enum(["Default", "TrustAll"]);
export type CertificateTrustModeEnumType = z.infer<typeof CertificateTrustModeEnum>;
