/*
 * This source code was auto-generated by TypeContractor.
 * Changes to this file may cause incorrect behavior and will be lost when the
 * code is regenerated next time TypeContractor runs.
 */
import { z } from 'zod';

export enum CloseBehavior {
  QuitApp = 0,
  MinimizeToTray = 1,
}

export const CloseBehaviorEnum = z.enum(["QuitApp", "MinimizeToTray"]);
export type CloseBehaviorEnumType = z.infer<typeof CloseBehaviorEnum>;
