/*
 * This source code was auto-generated by TypeContractor.
 * Changes to this file may cause incorrect behavior and will be lost when the
 * code is regenerated next time TypeContractor runs.
 */
import { z } from 'zod';

export enum ImapAuthMethod {
  Password = 0,
  OAuth2 = 1,
}

export const ImapAuthMethodEnum = z.enum(["Password", "OAuth2"]);
export type ImapAuthMethodEnumType = z.infer<typeof ImapAuthMethodEnum>;
