/*
 * This source code was auto-generated by TypeContractor.
 * Changes to this file may cause incorrect behavior and will be lost when the
 * code is regenerated next time TypeContractor runs.
 */
import { z } from 'zod';

export enum InitialSyncMode {
  LastNMonths = 0,
  LastNMessages = 1,
  Full = 2,
}

export const InitialSyncModeEnum = z.enum(["LastNMonths", "LastNMessages", "Full"]);
export type InitialSyncModeEnumType = z.infer<typeof InitialSyncModeEnum>;
