/*
 * This source code was auto-generated by TypeContractor.
 * Changes to this file may cause incorrect behavior and will be lost when the
 * code is regenerated next time TypeContractor runs.
 */
import { z } from 'zod';

export enum MailTransportSecurity {
  None = 0,
  TlsOnConnect = 1,
  StartTls = 2,
}

export const MailTransportSecurityEnum = z.enum(["None", "TlsOnConnect", "StartTls"]);
export type MailTransportSecurityEnumType = z.infer<typeof MailTransportSecurityEnum>;
