/*
 * This source code was auto-generated by TypeContractor.
 * Changes to this file may cause incorrect behavior and will be lost when the
 * code is regenerated next time TypeContractor runs.
 */
import { z } from 'zod';

export enum ProviderType {
  Imap = 0,
  Gmail = 1,
  Microsoft365 = 2,
}

export const ProviderTypeEnum = z.enum(["Imap", "Gmail", "Microsoft365"]);
export type ProviderTypeEnumType = z.infer<typeof ProviderTypeEnum>;
