/*
 * This source code was auto-generated by TypeContractor.
 * Changes to this file may cause incorrect behavior and will be lost when the
 * code is regenerated next time TypeContractor runs.
 */
import { z } from 'zod';

export enum RemoteContentRuleDecision {
  Allow = 0,
  Block = 1,
}

export const RemoteContentRuleDecisionEnum = z.enum(["Allow", "Block"]);
export type RemoteContentRuleDecisionEnumType = z.infer<typeof RemoteContentRuleDecisionEnum>;
