/*
 * This source code was auto-generated by TypeContractor.
 * Changes to this file may cause incorrect behavior and will be lost when the
 * code is regenerated next time TypeContractor runs.
 */
import { z } from 'zod';

export enum RemoteContentRuleScope {
  Sender = 0,
  Domain = 1,
}

export const RemoteContentRuleScopeEnum = z.enum(["Sender", "Domain"]);
export type RemoteContentRuleScopeEnumType = z.infer<typeof RemoteContentRuleScopeEnum>;
