/*
 * This source code was auto-generated by TypeContractor.
 * Changes to this file may cause incorrect behavior and will be lost when the
 * code is regenerated next time TypeContractor runs.
 */
import { z } from 'zod';

export enum SmtpAuthMethod {
  None = 0,
  Password = 1,
  OAuth2 = 2,
}

export const SmtpAuthMethodEnum = z.enum(["None", "Password", "OAuth2"]);
export type SmtpAuthMethodEnumType = z.infer<typeof SmtpAuthMethodEnum>;
