/*
 * This source code was auto-generated by TypeContractor.
 * Changes to this file may cause incorrect behavior and will be lost when the
 * code is regenerated next time TypeContractor runs.
 */
import { z } from 'zod';

export enum ThemePreference {
  System = 0,
  Light = 1,
  Dark = 2,
}

export const ThemePreferenceEnum = z.enum(["System", "Light", "Dark"]);
export type ThemePreferenceEnumType = z.infer<typeof ThemePreferenceEnum>;
