// Generated by Tmds.DBus.Generator v0.95.0
// <auto-generated/>
#nullable enable
namespace MyloMail.Api.Credentials.SecretService
{
    sealed partial class Service : global::Tmds.DBus.Protocol.DBusObject
    {
        public const string DBusInterfaceName = "org.freedesktop.Secret.Service";
        public Service(global::Tmds.DBus.Protocol.DBusConnection connection, string destination, global::Tmds.DBus.Protocol.ObjectPath path)
            : base(connection, destination, path)
        { }
        public global::System.Threading.Tasks.Task<(global::Tmds.DBus.Protocol.VariantValue Output, global::Tmds.DBus.Protocol.ObjectPath Result)> OpenSessionAsync(string algorithm, global::Tmds.DBus.Protocol.VariantValue input)
        {
            return Connection.CallMethodAsync(CreateMessage(), (global::Tmds.DBus.Protocol.Message m, object? s) => MessageReader.Read_vo(m), this);
            global::Tmds.DBus.Protocol.MessageBuffer CreateMessage()
            {
                var writer = Connection.GetMessageWriter();
                writer.WriteMethodCallHeader(
                    destination: Destination,
                    path: Path,
                    @interface: DBusInterfaceName,
                    signature: "sv",
                    member: "OpenSession");
                writer.WriteString(algorithm);
                writer.WriteVariant(input);
                return writer.CreateMessage();
            }
        }
        public global::System.Threading.Tasks.Task<(global::Tmds.DBus.Protocol.ObjectPath[] Unlocked, global::Tmds.DBus.Protocol.ObjectPath[] Locked)> SearchItemsAsync(global::System.Collections.Generic.Dictionary<string, string> attributes)
        {
            return Connection.CallMethodAsync(CreateMessage(), (global::Tmds.DBus.Protocol.Message m, object? s) => MessageReader.Read_aoao(m), this);
            global::Tmds.DBus.Protocol.MessageBuffer CreateMessage()
            {
                var writer = Connection.GetMessageWriter();
                writer.WriteMethodCallHeader(
                    destination: Destination,
                    path: Path,
                    @interface: DBusInterfaceName,
                    signature: "a{ss}",
                    member: "SearchItems");
                writer.Write_aess(attributes);
                return writer.CreateMessage();
            }
        }
        public global::System.Threading.Tasks.Task<global::Tmds.DBus.Protocol.ObjectPath> ReadAliasAsync(string name)
        {
            return Connection.CallMethodAsync(CreateMessage(), (global::Tmds.DBus.Protocol.Message m, object? s) => MessageReader.Read_o(m), this);
            global::Tmds.DBus.Protocol.MessageBuffer CreateMessage()
            {
                var writer = Connection.GetMessageWriter();
                writer.WriteMethodCallHeader(
                    destination: Destination,
                    path: Path,
                    @interface: DBusInterfaceName,
                    signature: "s",
                    member: "ReadAlias");
                writer.WriteString(name);
                return writer.CreateMessage();
            }
        }
        public global::System.Threading.Tasks.Task<(global::Tmds.DBus.Protocol.ObjectPath[] Unlocked, global::Tmds.DBus.Protocol.ObjectPath Prompt)> UnlockAsync(global::Tmds.DBus.Protocol.ObjectPath[] objects)
        {
            return Connection.CallMethodAsync(CreateMessage(), (global::Tmds.DBus.Protocol.Message m, object? s) => MessageReader.Read_aoo(m), this);
            global::Tmds.DBus.Protocol.MessageBuffer CreateMessage()
            {
                var writer = Connection.GetMessageWriter();
                writer.WriteMethodCallHeader(
                    destination: Destination,
                    path: Path,
                    @interface: DBusInterfaceName,
                    signature: "ao",
                    member: "Unlock");
                writer.WriteArray(objects);
                return writer.CreateMessage();
            }
        }
    }
    sealed partial class Collection : global::Tmds.DBus.Protocol.DBusObject
    {
        public const string DBusInterfaceName = "org.freedesktop.Secret.Collection";
        public Collection(global::Tmds.DBus.Protocol.DBusConnection connection, string destination, global::Tmds.DBus.Protocol.ObjectPath path)
            : base(connection, destination, path)
        { }
        public global::System.Threading.Tasks.Task<(global::Tmds.DBus.Protocol.ObjectPath Item, global::Tmds.DBus.Protocol.ObjectPath Prompt)> CreateItemAsync(global::System.Collections.Generic.Dictionary<string, global::Tmds.DBus.Protocol.VariantValue> properties, (global::Tmds.DBus.Protocol.ObjectPath, byte[], byte[], string) secret, bool replace)
        {
            return Connection.CallMethodAsync(CreateMessage(), (global::Tmds.DBus.Protocol.Message m, object? s) => MessageReader.Read_oo(m), this);
            global::Tmds.DBus.Protocol.MessageBuffer CreateMessage()
            {
                var writer = Connection.GetMessageWriter();
                writer.WriteMethodCallHeader(
                    destination: Destination,
                    path: Path,
                    @interface: DBusInterfaceName,
                    signature: "a{sv}(oayays)b",
                    member: "CreateItem");
                writer.WriteDictionary(properties);
                writer.Write_roayaysz(secret);
                writer.WriteBool(replace);
                return writer.CreateMessage();
            }
        }
    }
    sealed partial class Item : global::Tmds.DBus.Protocol.DBusObject
    {
        public const string DBusInterfaceName = "org.freedesktop.Secret.Item";
        public Item(global::Tmds.DBus.Protocol.DBusConnection connection, string destination, global::Tmds.DBus.Protocol.ObjectPath path)
            : base(connection, destination, path)
        { }
        public global::System.Threading.Tasks.Task<global::Tmds.DBus.Protocol.ObjectPath> DeleteAsync()
        {
            return Connection.CallMethodAsync(CreateMessage(), (global::Tmds.DBus.Protocol.Message m, object? s) => MessageReader.Read_o(m), this);
            global::Tmds.DBus.Protocol.MessageBuffer CreateMessage()
            {
                var writer = Connection.GetMessageWriter();
                writer.WriteMethodCallHeader(
                    destination: Destination,
                    path: Path,
                    @interface: DBusInterfaceName,
                    member: "Delete");
                return writer.CreateMessage();
            }
        }
        public global::System.Threading.Tasks.Task<(global::Tmds.DBus.Protocol.ObjectPath, byte[], byte[], string)> GetSecretAsync(global::Tmds.DBus.Protocol.ObjectPath session)
        {
            return Connection.CallMethodAsync(CreateMessage(), (global::Tmds.DBus.Protocol.Message m, object? s) => MessageReader.Read_roayaysz(m), this);
            global::Tmds.DBus.Protocol.MessageBuffer CreateMessage()
            {
                var writer = Connection.GetMessageWriter();
                writer.WriteMethodCallHeader(
                    destination: Destination,
                    path: Path,
                    @interface: DBusInterfaceName,
                    signature: "o",
                    member: "GetSecret");
                writer.WriteObjectPath(session);
                return writer.CreateMessage();
            }
        }
    }
    sealed partial class Prompt : global::Tmds.DBus.Protocol.DBusObject
    {
        public const string DBusInterfaceName = "org.freedesktop.Secret.Prompt";
        public Prompt(global::Tmds.DBus.Protocol.DBusConnection connection, string destination, global::Tmds.DBus.Protocol.ObjectPath path)
            : base(connection, destination, path)
        { }
        public global::System.Threading.Tasks.Task PromptAsync(string windowId)
        {
            return Connection.CallMethodAsync(CreateMessage());
            global::Tmds.DBus.Protocol.MessageBuffer CreateMessage()
            {
                var writer = Connection.GetMessageWriter();
                writer.WriteMethodCallHeader(
                    destination: Destination,
                    path: Path,
                    @interface: DBusInterfaceName,
                    signature: "s",
                    member: "Prompt");
                writer.WriteString(windowId);
                return writer.CreateMessage();
            }
        }
        public global::System.Threading.Tasks.ValueTask<global::System.IDisposable> WatchCompletedAsync(global::System.Action<(bool Dismissed, global::Tmds.DBus.Protocol.VariantValue Result)> handler, bool emitOnCapturedContext = true)
            => WatchCompletedAsync(static (global::Tmds.DBus.Protocol.Notification<(bool Dismissed, global::Tmds.DBus.Protocol.VariantValue Result)> n) => ((global::System.Action<(bool Dismissed, global::Tmds.DBus.Protocol.VariantValue Result)>)n.State!)(n.Value), global::Tmds.DBus.Protocol.ObserverFlags.None, emitOnCapturedContext, handler);
        public global::System.Threading.Tasks.ValueTask<global::System.IDisposable> WatchCompletedAsync(global::System.Func<(bool Dismissed, global::Tmds.DBus.Protocol.VariantValue Result), global::System.Threading.Tasks.ValueTask> handler, bool emitOnCapturedContext = true)
            => WatchCompletedAsync(static (global::Tmds.DBus.Protocol.Notification<(bool Dismissed, global::Tmds.DBus.Protocol.VariantValue Result)> n) => ((global::System.Func<(bool Dismissed, global::Tmds.DBus.Protocol.VariantValue Result), global::System.Threading.Tasks.ValueTask>)n.State!)(n.Value), global::Tmds.DBus.Protocol.ObserverFlags.None, emitOnCapturedContext, handler);
        public global::System.Threading.Tasks.ValueTask<global::System.IDisposable> WatchCompletedAsync(global::System.Action<global::Tmds.DBus.Protocol.Notification<(bool Dismissed, global::Tmds.DBus.Protocol.VariantValue Result)>> handler, global::Tmds.DBus.Protocol.ObserverFlags flags, bool emitOnCapturedContext = true, object? state = null)
            => Connection.WatchSignalAsync(Destination, Path, DBusInterfaceName, "Completed", (global::Tmds.DBus.Protocol.Message m, object? s) => MessageReader.Read_bv(m), handler, flags, emitOnCapturedContext, state);
        public global::System.Threading.Tasks.ValueTask<global::System.IDisposable> WatchCompletedAsync(global::System.Func<global::Tmds.DBus.Protocol.Notification<(bool Dismissed, global::Tmds.DBus.Protocol.VariantValue Result)>, global::System.Threading.Tasks.ValueTask> handler, global::Tmds.DBus.Protocol.ObserverFlags flags, bool emitOnCapturedContext = true, object? state = null)
            => Connection.WatchSignalAsync(Destination, Path, DBusInterfaceName, "Completed", (global::Tmds.DBus.Protocol.Message m, object? s) => MessageReader.Read_bv(m), handler, flags, emitOnCapturedContext, state);
    }
    static partial class ObjectFactory
    {
        public static Service CreateService(this global::Tmds.DBus.Protocol.DBusService service, global::Tmds.DBus.Protocol.ObjectPath path) => new Service(service.Connection, service.Name, path);
        public static Collection CreateCollection(this global::Tmds.DBus.Protocol.DBusService service, global::Tmds.DBus.Protocol.ObjectPath path) => new Collection(service.Connection, service.Name, path);
        public static Item CreateItem(this global::Tmds.DBus.Protocol.DBusService service, global::Tmds.DBus.Protocol.ObjectPath path) => new Item(service.Connection, service.Name, path);
        public static Prompt CreatePrompt(this global::Tmds.DBus.Protocol.DBusService service, global::Tmds.DBus.Protocol.ObjectPath path) => new Prompt(service.Connection, service.Name, path);
    }
    file static class MessageReader
    {
        public static (global::Tmds.DBus.Protocol.VariantValue, global::Tmds.DBus.Protocol.ObjectPath) Read_vo(global::Tmds.DBus.Protocol.Message message)
        {
            var reader = message.GetBodyReader();
            var arg0 = reader.ReadVariantValue();
            var arg1 = reader.ReadObjectPath();
            return (arg0, arg1);
        }
        public static (global::Tmds.DBus.Protocol.ObjectPath[], global::Tmds.DBus.Protocol.ObjectPath[]) Read_aoao(global::Tmds.DBus.Protocol.Message message)
        {
            var reader = message.GetBodyReader();
            var arg0 = reader.ReadArrayOfObjectPath();
            var arg1 = reader.ReadArrayOfObjectPath();
            return (arg0, arg1);
        }
        public static global::Tmds.DBus.Protocol.ObjectPath Read_o(global::Tmds.DBus.Protocol.Message message)
        {
            var reader = message.GetBodyReader();
            return reader.ReadObjectPath();
        }
        public static (global::Tmds.DBus.Protocol.ObjectPath[], global::Tmds.DBus.Protocol.ObjectPath) Read_aoo(global::Tmds.DBus.Protocol.Message message)
        {
            var reader = message.GetBodyReader();
            var arg0 = reader.ReadArrayOfObjectPath();
            var arg1 = reader.ReadObjectPath();
            return (arg0, arg1);
        }
        public static (global::Tmds.DBus.Protocol.ObjectPath, global::Tmds.DBus.Protocol.ObjectPath) Read_oo(global::Tmds.DBus.Protocol.Message message)
        {
            var reader = message.GetBodyReader();
            var arg0 = reader.ReadObjectPath();
            var arg1 = reader.ReadObjectPath();
            return (arg0, arg1);
        }
        public static (global::Tmds.DBus.Protocol.ObjectPath, byte[], byte[], string) Read_roayaysz(global::Tmds.DBus.Protocol.Message message)
        {
            var reader = message.GetBodyReader();
            return reader.Read_roayaysz();
        }
        public static (bool, global::Tmds.DBus.Protocol.VariantValue) Read_bv(global::Tmds.DBus.Protocol.Message message)
        {
            var reader = message.GetBodyReader();
            var arg0 = reader.ReadBool();
            var arg1 = reader.ReadVariantValue();
            return (arg0, arg1);
        }
        public static (global::Tmds.DBus.Protocol.ObjectPath, byte[], byte[], string) Read_roayaysz(this ref global::Tmds.DBus.Protocol.Reader reader)
        {
            reader.AlignStruct();
            return (reader.ReadObjectPath(), reader.ReadArrayOfByte(), reader.ReadArrayOfByte(), reader.ReadString());
        }
    }
    file static class MessageWriterExtensions
    {
        public static void Write_aess(this ref global::Tmds.DBus.Protocol.MessageWriter writer, global::System.Collections.Generic.Dictionary<string, string> value)
        {
            global::Tmds.DBus.Protocol.ArrayStart arrayStart = writer.WriteDictionaryStart();
            foreach (var item in value)
            {
                writer.WriteDictionaryEntryStart();
                writer.WriteString(item.Key);
                writer.WriteString(item.Value);
            }
            writer.WriteDictionaryEnd(arrayStart);
        }
        public static void Write_roayaysz(this ref global::Tmds.DBus.Protocol.MessageWriter writer, (global::Tmds.DBus.Protocol.ObjectPath, byte[], byte[], string) value)
        {
            writer.WriteStructureStart();
            writer.WriteObjectPath(value.Item1);
            writer.WriteArray(value.Item2);
            writer.WriteArray(value.Item3);
            writer.WriteString(value.Item4);
        }
    }
}
