name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  check:
    if: github.ref_type != 'tag' && github.event_name != 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: pnpm
      - run: dotnet tool restore
      - run: pnpm install --frozen-lockfile
      - run: pnpm generate:types
      - run: pnpm check

  cross-platform-check:
    if: github.ref_type == 'tag' || github.event_name == 'workflow_dispatch'
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: pnpm
      - run: dotnet tool restore
      - run: pnpm install --frozen-lockfile
      - run: pnpm generate:types
      - run: pnpm check
